// <auto-generated />
namespace DebugMcIf
{
	partial class FormSwitching
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this._btnInterlockXY = new System.Windows.Forms.Button();
			this._btnIncrimentalReferenceAxisMove = new System.Windows.Forms.Button();
			this._btnReqTouchSensor = new System.Windows.Forms.Button();
			this._btnReqOptionalStopOn = new System.Windows.Forms.Button();
			this._btnReqHandlePermitOn = new System.Windows.Forms.Button();
			this._btnCancel = new System.Windows.Forms.Button();
			this._btnAecByLife = new System.Windows.Forms.Button();
			this._btnDryRun = new System.Windows.Forms.Button();
			this._btnInitialSet = new System.Windows.Forms.Button();
			this._chkOneTime = new System.Windows.Forms.CheckBox();
			this._grpSendingBack = new System.Windows.Forms.GroupBox();
			this._btnReqSendBackSignal = new System.Windows.Forms.Button();
			this._btnReqSendBack = new System.Windows.Forms.Button();
			this._grpSwtiching = new System.Windows.Forms.GroupBox();
			this._btnReqMachineLock = new System.Windows.Forms.Button();
			this._btnBlockSkip = new System.Windows.Forms.Button();
			this._btnCorrectAngle = new System.Windows.Forms.Button();
			this._btnPartitionRoundStop = new System.Windows.Forms.Button();
			this._btnReqShutDown = new System.Windows.Forms.Button();
			this._btnAutoModeOutput = new System.Windows.Forms.Button();
			this._btnBuzzer = new System.Windows.Forms.Button();
			this._btnReqShowMessageSignal = new System.Windows.Forms.Button();
			this._btnReqShowMessage = new System.Windows.Forms.Button();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this._edtButtonNumber = new System.Windows.Forms.NumericUpDown();
			this._edtInputNumber = new System.Windows.Forms.NumericUpDown();
			this._btnReqShowMessageAnswer = new System.Windows.Forms.Button();
			this._stcReqShowMessage = new System.Windows.Forms.Label();
			this._grpSendingBack.SuspendLayout();
			this._grpSwtiching.SuspendLayout();
			this.groupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtButtonNumber)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtInputNumber)).BeginInit();
			this.SuspendLayout();
			// 
			// _btnInterlockXY
			// 
			this._btnInterlockXY.Location = new System.Drawing.Point(11, 162);
			this._btnInterlockXY.Name = "_btnInterlockXY";
			this._btnInterlockXY.Size = new System.Drawing.Size(120, 30);
			this._btnInterlockXY.TabIndex = 45;
			this._btnInterlockXY.Text = "XY_ILOCK";
			this._btnInterlockXY.UseVisualStyleBackColor = true;
			this._btnInterlockXY.Click += new System.EventHandler(this._btnInterlockXY_Click);
			// 
			// _btnIncrimentalReferenceAxisMove
			// 
			this._btnIncrimentalReferenceAxisMove.Location = new System.Drawing.Point(11, 126);
			this._btnIncrimentalReferenceAxisMove.Name = "_btnIncrimentalReferenceAxisMove";
			this._btnIncrimentalReferenceAxisMove.Size = new System.Drawing.Size(120, 30);
			this._btnIncrimentalReferenceAxisMove.TabIndex = 44;
			this._btnIncrimentalReferenceAxisMove.Text = "INCREFSET_MOV";
			this._btnIncrimentalReferenceAxisMove.UseVisualStyleBackColor = true;
			this._btnIncrimentalReferenceAxisMove.Click += new System.EventHandler(this._btnIncrimentalReferenceAxisMove_Click);
			// 
			// _btnReqTouchSensor
			// 
			this._btnReqTouchSensor.Location = new System.Drawing.Point(11, 90);
			this._btnReqTouchSensor.Name = "_btnReqTouchSensor";
			this._btnReqTouchSensor.Size = new System.Drawing.Size(120, 30);
			this._btnReqTouchSensor.TabIndex = 43;
			this._btnReqTouchSensor.Text = "TOUCHSENSE";
			this._btnReqTouchSensor.UseVisualStyleBackColor = true;
			this._btnReqTouchSensor.Click += new System.EventHandler(this._btnReqTouchSensor_Click);
			// 
			// _btnReqOptionalStopOn
			// 
			this._btnReqOptionalStopOn.Location = new System.Drawing.Point(11, 54);
			this._btnReqOptionalStopOn.Name = "_btnReqOptionalStopOn";
			this._btnReqOptionalStopOn.Size = new System.Drawing.Size(120, 30);
			this._btnReqOptionalStopOn.TabIndex = 41;
			this._btnReqOptionalStopOn.Text = "OPT. STOP";
			this._btnReqOptionalStopOn.UseVisualStyleBackColor = true;
			this._btnReqOptionalStopOn.Click += new System.EventHandler(this._btnReqOptionalStopOn_Click);
			// 
			// _btnReqHandlePermitOn
			// 
			this._btnReqHandlePermitOn.Location = new System.Drawing.Point(11, 18);
			this._btnReqHandlePermitOn.Name = "_btnReqHandlePermitOn";
			this._btnReqHandlePermitOn.Size = new System.Drawing.Size(120, 30);
			this._btnReqHandlePermitOn.TabIndex = 42;
			this._btnReqHandlePermitOn.Text = "HANDLEPERMIT";
			this._btnReqHandlePermitOn.UseVisualStyleBackColor = true;
			this._btnReqHandlePermitOn.Click += new System.EventHandler(this._btnReqHandlePermitOn_Click);
			// 
			// _btnCancel
			// 
			this._btnCancel.Location = new System.Drawing.Point(544, 278);
			this._btnCancel.Name = "_btnCancel";
			this._btnCancel.Size = new System.Drawing.Size(120, 30);
			this._btnCancel.TabIndex = 46;
			this._btnCancel.Text = "CANCEL";
			this._btnCancel.UseVisualStyleBackColor = true;
			this._btnCancel.Click += new System.EventHandler(this._btnCancel_Click);
			// 
			// _btnAecByLife
			// 
			this._btnAecByLife.Location = new System.Drawing.Point(137, 18);
			this._btnAecByLife.Name = "_btnAecByLife";
			this._btnAecByLife.Size = new System.Drawing.Size(120, 30);
			this._btnAecByLife.TabIndex = 47;
			this._btnAecByLife.Text = "ELCTDCHGEN";
			this._btnAecByLife.UseVisualStyleBackColor = true;
			this._btnAecByLife.Click += new System.EventHandler(this._btnAecByLife_Click);
			// 
			// _btnDryRun
			// 
			this._btnDryRun.Location = new System.Drawing.Point(137, 54);
			this._btnDryRun.Name = "_btnDryRun";
			this._btnDryRun.Size = new System.Drawing.Size(120, 30);
			this._btnDryRun.TabIndex = 48;
			this._btnDryRun.Text = "DRYRUN";
			this._btnDryRun.UseVisualStyleBackColor = true;
			this._btnDryRun.Click += new System.EventHandler(this._btnDryRun_Click);
			// 
			// _btnInitialSet
			// 
			this._btnInitialSet.Location = new System.Drawing.Point(137, 90);
			this._btnInitialSet.Name = "_btnInitialSet";
			this._btnInitialSet.Size = new System.Drawing.Size(120, 30);
			this._btnInitialSet.TabIndex = 49;
			this._btnInitialSet.Text = "INITIALSET";
			this._btnInitialSet.UseVisualStyleBackColor = true;
			this._btnInitialSet.Click += new System.EventHandler(this._btnInitialSet_Click);
			// 
			// _chkOneTime
			// 
			this._chkOneTime.AutoSize = true;
			this._chkOneTime.Checked = true;
			this._chkOneTime.CheckState = System.Windows.Forms.CheckState.Checked;
			this._chkOneTime.Location = new System.Drawing.Point(461, 286);
			this._chkOneTime.Name = "_chkOneTime";
			this._chkOneTime.Size = new System.Drawing.Size(77, 16);
			this._chkOneTime.TabIndex = 50;
			this._chkOneTime.Text = "ONE TIME";
			this._chkOneTime.UseVisualStyleBackColor = true;
			// 
			// _grpSendingBack
			// 
			this._grpSendingBack.Controls.Add(this._btnReqSendBackSignal);
			this._grpSendingBack.Controls.Add(this._btnReqSendBack);
			this._grpSendingBack.Location = new System.Drawing.Point(281, 2);
			this._grpSendingBack.Name = "_grpSendingBack";
			this._grpSendingBack.Size = new System.Drawing.Size(204, 52);
			this._grpSendingBack.TabIndex = 51;
			this._grpSendingBack.TabStop = false;
			this._grpSendingBack.Text = "SENDING BACK";
			// 
			// _btnReqSendBackSignal
			// 
			this._btnReqSendBackSignal.Location = new System.Drawing.Point(9, 16);
			this._btnReqSendBackSignal.Name = "_btnReqSendBackSignal";
			this._btnReqSendBackSignal.Size = new System.Drawing.Size(60, 30);
			this._btnReqSendBackSignal.TabIndex = 35;
			this._btnReqSendBackSignal.Text = "SIGNAL";
			this._btnReqSendBackSignal.UseVisualStyleBackColor = true;
			this._btnReqSendBackSignal.Click += new System.EventHandler(this._btnReqSendBackSignal_Click);
			// 
			// _btnReqSendBack
			// 
			this._btnReqSendBack.Location = new System.Drawing.Point(75, 16);
			this._btnReqSendBack.Name = "_btnReqSendBack";
			this._btnReqSendBack.Size = new System.Drawing.Size(120, 30);
			this._btnReqSendBack.TabIndex = 23;
			this._btnReqSendBack.Text = "RETURN";
			this._btnReqSendBack.UseVisualStyleBackColor = true;
			this._btnReqSendBack.Click += new System.EventHandler(this._btnReqSendBack_Click);
			// 
			// _grpSwtiching
			// 
			this._grpSwtiching.Controls.Add(this._btnReqMachineLock);
			this._grpSwtiching.Controls.Add(this._btnBlockSkip);
			this._grpSwtiching.Controls.Add(this._btnCorrectAngle);
			this._grpSwtiching.Controls.Add(this._btnPartitionRoundStop);
			this._grpSwtiching.Controls.Add(this._btnReqShutDown);
			this._grpSwtiching.Controls.Add(this._btnAutoModeOutput);
			this._grpSwtiching.Controls.Add(this._btnBuzzer);
			this._grpSwtiching.Controls.Add(this._btnReqHandlePermitOn);
			this._grpSwtiching.Controls.Add(this._btnAecByLife);
			this._grpSwtiching.Controls.Add(this._btnDryRun);
			this._grpSwtiching.Controls.Add(this._btnInitialSet);
			this._grpSwtiching.Controls.Add(this._btnInterlockXY);
			this._grpSwtiching.Controls.Add(this._btnReqOptionalStopOn);
			this._grpSwtiching.Controls.Add(this._btnIncrimentalReferenceAxisMove);
			this._grpSwtiching.Controls.Add(this._btnReqTouchSensor);
			this._grpSwtiching.Location = new System.Drawing.Point(10, 2);
			this._grpSwtiching.Name = "_grpSwtiching";
			this._grpSwtiching.Size = new System.Drawing.Size(265, 306);
			this._grpSwtiching.TabIndex = 52;
			this._grpSwtiching.TabStop = false;
			this._grpSwtiching.Text = "SWITCH";
			// 
			// _btnReqMachineLock
			// 
			this._btnReqMachineLock.Location = new System.Drawing.Point(137, 234);
			this._btnReqMachineLock.Name = "_btnReqMachineLock";
			this._btnReqMachineLock.Size = new System.Drawing.Size(120, 30);
			this._btnReqMachineLock.TabIndex = 56;
			this._btnReqMachineLock.Text = "MAC. LOCK";
			this._btnReqMachineLock.UseVisualStyleBackColor = true;
			this._btnReqMachineLock.Click += new System.EventHandler(this._btnReqMachineLock_Click);
			// 
			// _btnBlockSkip
			// 
			this._btnBlockSkip.Location = new System.Drawing.Point(11, 269);
			this._btnBlockSkip.Name = "_btnBlockSkip";
			this._btnBlockSkip.Size = new System.Drawing.Size(120, 30);
			this._btnBlockSkip.TabIndex = 55;
			this._btnBlockSkip.Text = "BLOCK SKIP";
			this._btnBlockSkip.UseVisualStyleBackColor = true;
			this._btnBlockSkip.Click += new System.EventHandler(this._btnBlockSkip_Click);
			// 
			// _btnCorrectAngle
			// 
			this._btnCorrectAngle.Location = new System.Drawing.Point(11, 233);
			this._btnCorrectAngle.Name = "_btnCorrectAngle";
			this._btnCorrectAngle.Size = new System.Drawing.Size(120, 30);
			this._btnCorrectAngle.TabIndex = 54;
			this._btnCorrectAngle.Text = "CORRECT ANGLE";
			this._btnCorrectAngle.UseVisualStyleBackColor = true;
			this._btnCorrectAngle.Click += new System.EventHandler(this._btnCorrectAngle_Click);
			// 
			// _btnPartitionRoundStop
			// 
			this._btnPartitionRoundStop.Location = new System.Drawing.Point(137, 198);
			this._btnPartitionRoundStop.Name = "_btnPartitionRoundStop";
			this._btnPartitionRoundStop.Size = new System.Drawing.Size(120, 30);
			this._btnPartitionRoundStop.TabIndex = 53;
			this._btnPartitionRoundStop.Text = "PTN. ROUND STOP";
			this._btnPartitionRoundStop.UseVisualStyleBackColor = true;
			this._btnPartitionRoundStop.Click += new System.EventHandler(this._btnPartitionRoundStop_Click);
			// 
			// _btnReqShutDown
			// 
			this._btnReqShutDown.Location = new System.Drawing.Point(11, 197);
			this._btnReqShutDown.Name = "_btnReqShutDown";
			this._btnReqShutDown.Size = new System.Drawing.Size(120, 30);
			this._btnReqShutDown.TabIndex = 52;
			this._btnReqShutDown.Text = "REQ. SHUTDOWN";
			this._btnReqShutDown.UseVisualStyleBackColor = true;
			this._btnReqShutDown.Click += new System.EventHandler(this._btnReqShutDown_Click);
			// 
			// _btnAutoModeOutput
			// 
			this._btnAutoModeOutput.Location = new System.Drawing.Point(137, 162);
			this._btnAutoModeOutput.Name = "_btnAutoModeOutput";
			this._btnAutoModeOutput.Size = new System.Drawing.Size(120, 30);
			this._btnAutoModeOutput.TabIndex = 51;
			this._btnAutoModeOutput.Text = "AUTO MODE O.";
			this._btnAutoModeOutput.UseVisualStyleBackColor = true;
			this._btnAutoModeOutput.Click += new System.EventHandler(this._btnAutoModeOutput_Click);
			// 
			// _btnBuzzer
			// 
			this._btnBuzzer.Location = new System.Drawing.Point(137, 126);
			this._btnBuzzer.Name = "_btnBuzzer";
			this._btnBuzzer.Size = new System.Drawing.Size(120, 30);
			this._btnBuzzer.TabIndex = 50;
			this._btnBuzzer.Text = "BUZZER";
			this._btnBuzzer.UseVisualStyleBackColor = true;
			this._btnBuzzer.Click += new System.EventHandler(this._btnBuzzer_Click);
			// 
			// _btnReqShowMessageSignal
			// 
			this._btnReqShowMessageSignal.Location = new System.Drawing.Point(9, 18);
			this._btnReqShowMessageSignal.Name = "_btnReqShowMessageSignal";
			this._btnReqShowMessageSignal.Size = new System.Drawing.Size(60, 30);
			this._btnReqShowMessageSignal.TabIndex = 53;
			this._btnReqShowMessageSignal.Text = "SIGNAL";
			this._btnReqShowMessageSignal.UseVisualStyleBackColor = true;
			this._btnReqShowMessageSignal.Click += new System.EventHandler(this._btnReqShowMessageSignal_Click);
			// 
			// _btnReqShowMessage
			// 
			this._btnReqShowMessage.Location = new System.Drawing.Point(76, 18);
			this._btnReqShowMessage.Name = "_btnReqShowMessage";
			this._btnReqShowMessage.Size = new System.Drawing.Size(120, 30);
			this._btnReqShowMessage.TabIndex = 54;
			this._btnReqShowMessage.Text = "RETURN";
			this._btnReqShowMessage.UseVisualStyleBackColor = true;
			this._btnReqShowMessage.Click += new System.EventHandler(this._btnReqShowMessage_Click);
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this._edtButtonNumber);
			this.groupBox1.Controls.Add(this._edtInputNumber);
			this.groupBox1.Controls.Add(this._btnReqShowMessageAnswer);
			this.groupBox1.Controls.Add(this._stcReqShowMessage);
			this.groupBox1.Controls.Add(this._btnReqShowMessageSignal);
			this.groupBox1.Controls.Add(this._btnReqShowMessage);
			this.groupBox1.Location = new System.Drawing.Point(281, 60);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(383, 90);
			this.groupBox1.TabIndex = 55;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "SHOW MESSAGE";
			// 
			// _edtButtonNumber
			// 
			this._edtButtonNumber.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtButtonNumber.Location = new System.Drawing.Point(200, 54);
			this._edtButtonNumber.Name = "_edtButtonNumber";
			this._edtButtonNumber.Size = new System.Drawing.Size(53, 31);
			this._edtButtonNumber.TabIndex = 58;
			this._edtButtonNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _edtInputNumber
			// 
			this._edtInputNumber.DecimalPlaces = 3;
			this._edtInputNumber.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtInputNumber.Location = new System.Drawing.Point(76, 54);
			this._edtInputNumber.Name = "_edtInputNumber";
			this._edtInputNumber.Size = new System.Drawing.Size(118, 31);
			this._edtInputNumber.TabIndex = 57;
			this._edtInputNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _btnReqShowMessageAnswer
			// 
			this._btnReqShowMessageAnswer.Location = new System.Drawing.Point(259, 55);
			this._btnReqShowMessageAnswer.Name = "_btnReqShowMessageAnswer";
			this._btnReqShowMessageAnswer.Size = new System.Drawing.Size(120, 30);
			this._btnReqShowMessageAnswer.TabIndex = 56;
			this._btnReqShowMessageAnswer.Text = "ANSWER";
			this._btnReqShowMessageAnswer.UseVisualStyleBackColor = true;
			this._btnReqShowMessageAnswer.Click += new System.EventHandler(this._btnReqShowMessageAnswer_Click);
			// 
			// _stcReqShowMessage
			// 
			this._stcReqShowMessage.AutoSize = true;
			this._stcReqShowMessage.Location = new System.Drawing.Point(197, 27);
			this._stcReqShowMessage.Name = "_stcReqShowMessage";
			this._stcReqShowMessage.Size = new System.Drawing.Size(48, 12);
			this._stcReqShowMessage.TabIndex = 55;
			this._stcReqShowMessage.Text = "RESULT";
			// 
			// FormSwitching
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.SystemColors.ControlDark;
			this.ClientSize = new System.Drawing.Size(675, 320);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this._grpSwtiching);
			this.Controls.Add(this._grpSendingBack);
			this.Controls.Add(this._chkOneTime);
			this.Controls.Add(this._btnCancel);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
			this.Name = "FormSwitching";
			this.ShowInTaskbar = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "FormSwitching";
			this.Deactivate += new System.EventHandler(this.FormSwitching_Deactivate);
			this.Load += new System.EventHandler(this.FormSwitching_Load);
			this._grpSendingBack.ResumeLayout(false);
			this._grpSwtiching.ResumeLayout(false);
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtButtonNumber)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtInputNumber)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button _btnInterlockXY;
		private System.Windows.Forms.Button _btnIncrimentalReferenceAxisMove;
		private System.Windows.Forms.Button _btnReqTouchSensor;
		private System.Windows.Forms.Button _btnReqOptionalStopOn;
		private System.Windows.Forms.Button _btnReqHandlePermitOn;
		private System.Windows.Forms.Button _btnCancel;
		private System.Windows.Forms.Button _btnAecByLife;
		private System.Windows.Forms.Button _btnDryRun;
		private System.Windows.Forms.Button _btnInitialSet;
		private System.Windows.Forms.CheckBox _chkOneTime;
		private System.Windows.Forms.GroupBox _grpSendingBack;
		private System.Windows.Forms.Button _btnReqSendBackSignal;
		private System.Windows.Forms.Button _btnReqSendBack;
		private System.Windows.Forms.GroupBox _grpSwtiching;
		private System.Windows.Forms.Button _btnBuzzer;
		private System.Windows.Forms.Button _btnAutoModeOutput;
		private System.Windows.Forms.Button _btnReqShutDown;
		private System.Windows.Forms.Button _btnReqShowMessageSignal;
		private System.Windows.Forms.Button _btnReqShowMessage;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.Label _stcReqShowMessage;
		private System.Windows.Forms.Button _btnReqShowMessageAnswer;
		private System.Windows.Forms.NumericUpDown _edtButtonNumber;
		private System.Windows.Forms.NumericUpDown _edtInputNumber;
		private System.Windows.Forms.Button _btnPartitionRoundStop;
		private System.Windows.Forms.Button _btnCorrectAngle;
		private System.Windows.Forms.Button _btnBlockSkip;
		private System.Windows.Forms.Button _btnReqMachineLock;
	}
}