// <auto-generated />
namespace DebugMcIf
{
	partial class FormPartitionSetting
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this._btnSet = new System.Windows.Forms.Button();
			this.label8 = new System.Windows.Forms.Label();
			this._chkThin6 = new System.Windows.Forms.CheckBox();
			this._edtEnd6 = new System.Windows.Forms.NumericUpDown();
			this._edtStart6 = new System.Windows.Forms.NumericUpDown();
			this.label7 = new System.Windows.Forms.Label();
			this._chkThin5 = new System.Windows.Forms.CheckBox();
			this._edtEnd5 = new System.Windows.Forms.NumericUpDown();
			this._edtStart5 = new System.Windows.Forms.NumericUpDown();
			this.label6 = new System.Windows.Forms.Label();
			this._chkThin4 = new System.Windows.Forms.CheckBox();
			this._edtEnd4 = new System.Windows.Forms.NumericUpDown();
			this._edtStart4 = new System.Windows.Forms.NumericUpDown();
			this.label5 = new System.Windows.Forms.Label();
			this._chkThin3 = new System.Windows.Forms.CheckBox();
			this._edtEnd3 = new System.Windows.Forms.NumericUpDown();
			this._edtStart3 = new System.Windows.Forms.NumericUpDown();
			this.label4 = new System.Windows.Forms.Label();
			this._chkThin2 = new System.Windows.Forms.CheckBox();
			this._edtEnd2 = new System.Windows.Forms.NumericUpDown();
			this._edtStart2 = new System.Windows.Forms.NumericUpDown();
			this.label3 = new System.Windows.Forms.Label();
			this._chkThin1 = new System.Windows.Forms.CheckBox();
			this._edtEnd1 = new System.Windows.Forms.NumericUpDown();
			this._edtStart1 = new System.Windows.Forms.NumericUpDown();
			this._btnGet = new System.Windows.Forms.Button();
			this._chkEnable = new System.Windows.Forms.CheckBox();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart1)).BeginInit();
			this.SuspendLayout();
			// 
			// _btnSet
			// 
			this._btnSet.Location = new System.Drawing.Point(106, 257);
			this._btnSet.Name = "_btnSet";
			this._btnSet.Size = new System.Drawing.Size(60, 30);
			this._btnSet.TabIndex = 31;
			this._btnSet.Text = "SET";
			this._btnSet.UseVisualStyleBackColor = true;
			this._btnSet.Click += new System.EventHandler(this._btnSet_Click);
			// 
			// label8
			// 
			this.label8.AutoSize = true;
			this.label8.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label8.Location = new System.Drawing.Point(9, 222);
			this.label8.Name = "label8";
			this.label8.Size = new System.Drawing.Size(34, 24);
			this.label8.TabIndex = 30;
			this.label8.Text = "#6";
			// 
			// _chkThin6
			// 
			this._chkThin6.AutoSize = true;
			this._chkThin6.Location = new System.Drawing.Point(182, 232);
			this._chkThin6.Name = "_chkThin6";
			this._chkThin6.Size = new System.Drawing.Size(50, 16);
			this._chkThin6.TabIndex = 27;
			this._chkThin6.Text = "THIN";
			this._chkThin6.UseVisualStyleBackColor = true;
			// 
			// _edtEnd6
			// 
			this._edtEnd6.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtEnd6.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtEnd6.Location = new System.Drawing.Point(116, 220);
			this._edtEnd6.Name = "_edtEnd6";
			this._edtEnd6.Size = new System.Drawing.Size(60, 31);
			this._edtEnd6.TabIndex = 29;
			this._edtEnd6.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _edtStart6
			// 
			this._edtStart6.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtStart6.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtStart6.Location = new System.Drawing.Point(49, 220);
			this._edtStart6.Name = "_edtStart6";
			this._edtStart6.Size = new System.Drawing.Size(60, 31);
			this._edtStart6.TabIndex = 28;
			this._edtStart6.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label7
			// 
			this.label7.AutoSize = true;
			this.label7.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label7.Location = new System.Drawing.Point(9, 185);
			this.label7.Name = "label7";
			this.label7.Size = new System.Drawing.Size(34, 24);
			this.label7.TabIndex = 26;
			this.label7.Text = "#5";
			// 
			// _chkThin5
			// 
			this._chkThin5.AutoSize = true;
			this._chkThin5.Location = new System.Drawing.Point(182, 195);
			this._chkThin5.Name = "_chkThin5";
			this._chkThin5.Size = new System.Drawing.Size(50, 16);
			this._chkThin5.TabIndex = 23;
			this._chkThin5.Text = "THIN";
			this._chkThin5.UseVisualStyleBackColor = true;
			// 
			// _edtEnd5
			// 
			this._edtEnd5.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtEnd5.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtEnd5.Location = new System.Drawing.Point(116, 183);
			this._edtEnd5.Name = "_edtEnd5";
			this._edtEnd5.Size = new System.Drawing.Size(60, 31);
			this._edtEnd5.TabIndex = 25;
			this._edtEnd5.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _edtStart5
			// 
			this._edtStart5.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtStart5.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtStart5.Location = new System.Drawing.Point(49, 183);
			this._edtStart5.Name = "_edtStart5";
			this._edtStart5.Size = new System.Drawing.Size(60, 31);
			this._edtStart5.TabIndex = 24;
			this._edtStart5.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label6
			// 
			this.label6.AutoSize = true;
			this.label6.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label6.Location = new System.Drawing.Point(9, 148);
			this.label6.Name = "label6";
			this.label6.Size = new System.Drawing.Size(34, 24);
			this.label6.TabIndex = 22;
			this.label6.Text = "#4";
			// 
			// _chkThin4
			// 
			this._chkThin4.AutoSize = true;
			this._chkThin4.Location = new System.Drawing.Point(182, 158);
			this._chkThin4.Name = "_chkThin4";
			this._chkThin4.Size = new System.Drawing.Size(50, 16);
			this._chkThin4.TabIndex = 19;
			this._chkThin4.Text = "THIN";
			this._chkThin4.UseVisualStyleBackColor = true;
			// 
			// _edtEnd4
			// 
			this._edtEnd4.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtEnd4.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtEnd4.Location = new System.Drawing.Point(116, 146);
			this._edtEnd4.Name = "_edtEnd4";
			this._edtEnd4.Size = new System.Drawing.Size(60, 31);
			this._edtEnd4.TabIndex = 21;
			this._edtEnd4.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _edtStart4
			// 
			this._edtStart4.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtStart4.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtStart4.Location = new System.Drawing.Point(49, 146);
			this._edtStart4.Name = "_edtStart4";
			this._edtStart4.Size = new System.Drawing.Size(60, 31);
			this._edtStart4.TabIndex = 20;
			this._edtStart4.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label5
			// 
			this.label5.AutoSize = true;
			this.label5.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label5.Location = new System.Drawing.Point(9, 114);
			this.label5.Name = "label5";
			this.label5.Size = new System.Drawing.Size(34, 24);
			this.label5.TabIndex = 18;
			this.label5.Text = "#3";
			// 
			// _chkThin3
			// 
			this._chkThin3.AutoSize = true;
			this._chkThin3.Location = new System.Drawing.Point(182, 121);
			this._chkThin3.Name = "_chkThin3";
			this._chkThin3.Size = new System.Drawing.Size(50, 16);
			this._chkThin3.TabIndex = 15;
			this._chkThin3.Text = "THIN";
			this._chkThin3.UseVisualStyleBackColor = true;
			// 
			// _edtEnd3
			// 
			this._edtEnd3.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtEnd3.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtEnd3.Location = new System.Drawing.Point(116, 109);
			this._edtEnd3.Name = "_edtEnd3";
			this._edtEnd3.Size = new System.Drawing.Size(60, 31);
			this._edtEnd3.TabIndex = 17;
			this._edtEnd3.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _edtStart3
			// 
			this._edtStart3.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtStart3.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtStart3.Location = new System.Drawing.Point(49, 109);
			this._edtStart3.Name = "_edtStart3";
			this._edtStart3.Size = new System.Drawing.Size(60, 31);
			this._edtStart3.TabIndex = 16;
			this._edtStart3.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label4
			// 
			this.label4.AutoSize = true;
			this.label4.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label4.Location = new System.Drawing.Point(9, 74);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(34, 24);
			this.label4.TabIndex = 14;
			this.label4.Text = "#2";
			// 
			// _chkThin2
			// 
			this._chkThin2.AutoSize = true;
			this._chkThin2.Location = new System.Drawing.Point(182, 84);
			this._chkThin2.Name = "_chkThin2";
			this._chkThin2.Size = new System.Drawing.Size(50, 16);
			this._chkThin2.TabIndex = 11;
			this._chkThin2.Text = "THIN";
			this._chkThin2.UseVisualStyleBackColor = true;
			// 
			// _edtEnd2
			// 
			this._edtEnd2.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtEnd2.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtEnd2.Location = new System.Drawing.Point(116, 72);
			this._edtEnd2.Name = "_edtEnd2";
			this._edtEnd2.Size = new System.Drawing.Size(60, 31);
			this._edtEnd2.TabIndex = 13;
			this._edtEnd2.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _edtStart2
			// 
			this._edtStart2.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtStart2.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtStart2.Location = new System.Drawing.Point(49, 72);
			this._edtStart2.Name = "_edtStart2";
			this._edtStart2.Size = new System.Drawing.Size(60, 31);
			this._edtStart2.TabIndex = 12;
			this._edtStart2.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label3
			// 
			this.label3.AutoSize = true;
			this.label3.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label3.Location = new System.Drawing.Point(9, 37);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(34, 24);
			this.label3.TabIndex = 10;
			this.label3.Text = "#1";
			// 
			// _chkThin1
			// 
			this._chkThin1.AutoSize = true;
			this._chkThin1.Location = new System.Drawing.Point(182, 47);
			this._chkThin1.Name = "_chkThin1";
			this._chkThin1.Size = new System.Drawing.Size(50, 16);
			this._chkThin1.TabIndex = 8;
			this._chkThin1.Text = "THIN";
			this._chkThin1.UseVisualStyleBackColor = true;
			// 
			// _edtEnd1
			// 
			this._edtEnd1.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtEnd1.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtEnd1.Location = new System.Drawing.Point(116, 35);
			this._edtEnd1.Name = "_edtEnd1";
			this._edtEnd1.Size = new System.Drawing.Size(60, 31);
			this._edtEnd1.TabIndex = 9;
			this._edtEnd1.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _edtStart1
			// 
			this._edtStart1.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtStart1.ImeMode = System.Windows.Forms.ImeMode.Disable;
			this._edtStart1.Location = new System.Drawing.Point(49, 35);
			this._edtStart1.Name = "_edtStart1";
			this._edtStart1.Size = new System.Drawing.Size(60, 31);
			this._edtStart1.TabIndex = 8;
			this._edtStart1.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _btnGet
			// 
			this._btnGet.Location = new System.Drawing.Point(172, 257);
			this._btnGet.Name = "_btnGet";
			this._btnGet.Size = new System.Drawing.Size(60, 30);
			this._btnGet.TabIndex = 31;
			this._btnGet.Text = "GET";
			this._btnGet.UseVisualStyleBackColor = true;
			this._btnGet.Click += new System.EventHandler(this._btnGet_Click);
			// 
			// _chkEnable
			// 
			this._chkEnable.AutoSize = true;
			this._chkEnable.Location = new System.Drawing.Point(13, 13);
			this._chkEnable.Name = "_chkEnable";
			this._chkEnable.Size = new System.Drawing.Size(76, 16);
			this._chkEnable.TabIndex = 32;
			this._chkEnable.Text = "ENABLED";
			this._chkEnable.UseVisualStyleBackColor = true;
			this._chkEnable.Click += new System.EventHandler(this._chkEnable_Click);
			// 
			// FormPartitionSetting
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(245, 298);
			this.Controls.Add(this._chkEnable);
			this.Controls.Add(this._btnGet);
			this.Controls.Add(this._btnSet);
			this.Controls.Add(this._chkThin6);
			this.Controls.Add(this.label8);
			this.Controls.Add(this._chkThin5);
			this.Controls.Add(this.label3);
			this.Controls.Add(this._chkThin4);
			this.Controls.Add(this._edtStart1);
			this.Controls.Add(this._chkThin3);
			this.Controls.Add(this.label7);
			this.Controls.Add(this._edtEnd6);
			this.Controls.Add(this._edtEnd1);
			this.Controls.Add(this.label6);
			this.Controls.Add(this._edtStart6);
			this.Controls.Add(this._chkThin1);
			this.Controls.Add(this.label4);
			this.Controls.Add(this._edtStart2);
			this.Controls.Add(this._edtEnd5);
			this.Controls.Add(this._edtEnd2);
			this.Controls.Add(this._edtStart5);
			this.Controls.Add(this._chkThin2);
			this.Controls.Add(this.label5);
			this.Controls.Add(this._edtStart3);
			this.Controls.Add(this._edtEnd4);
			this.Controls.Add(this._edtEnd3);
			this.Controls.Add(this._edtStart4);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
			this.Name = "FormPartitionSetting";
			this.ShowInTaskbar = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Partition Setting";
			this.Load += new System.EventHandler(this.FormPartitionSetting_Load);
			((System.ComponentModel.ISupportInitialize)(this._edtEnd6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtEnd1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtStart1)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button _btnSet;
		private System.Windows.Forms.Label label8;
		private System.Windows.Forms.CheckBox _chkThin6;
		private System.Windows.Forms.NumericUpDown _edtEnd6;
		private System.Windows.Forms.NumericUpDown _edtStart6;
		private System.Windows.Forms.Label label7;
		private System.Windows.Forms.CheckBox _chkThin5;
		private System.Windows.Forms.NumericUpDown _edtEnd5;
		private System.Windows.Forms.NumericUpDown _edtStart5;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.CheckBox _chkThin4;
		private System.Windows.Forms.NumericUpDown _edtEnd4;
		private System.Windows.Forms.NumericUpDown _edtStart4;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.CheckBox _chkThin3;
		private System.Windows.Forms.NumericUpDown _edtEnd3;
		private System.Windows.Forms.NumericUpDown _edtStart3;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.CheckBox _chkThin2;
		private System.Windows.Forms.NumericUpDown _edtEnd2;
		private System.Windows.Forms.NumericUpDown _edtStart2;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.CheckBox _chkThin1;
		private System.Windows.Forms.NumericUpDown _edtEnd1;
		private System.Windows.Forms.NumericUpDown _edtStart1;
		private System.Windows.Forms.Button _btnGet;
		private System.Windows.Forms.CheckBox _chkEnable;
	}
}