// <auto-generated />
namespace DebugMcIf
{
	partial class FormStartupSetting
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.groupBox7 = new System.Windows.Forms.GroupBox();
			this._chkEnableAxisA = new System.Windows.Forms.CheckBox();
			this._chkEnableAxisB = new System.Windows.Forms.CheckBox();
			this._chkEnableAxisC = new System.Windows.Forms.CheckBox();
			this._btnSet = new System.Windows.Forms.Button();
			this._chkEnableEsf = new System.Windows.Forms.CheckBox();
			this._chkEnableGsf = new System.Windows.Forms.CheckBox();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.groupBox7.SuspendLayout();
			this.groupBox1.SuspendLayout();
			this.SuspendLayout();
			// 
			// groupBox7
			// 
			this.groupBox7.Controls.Add(this._chkEnableAxisA);
			this.groupBox7.Controls.Add(this._chkEnableAxisB);
			this.groupBox7.Controls.Add(this._chkEnableAxisC);
			this.groupBox7.Location = new System.Drawing.Point(12, 12);
			this.groupBox7.Name = "groupBox7";
			this.groupBox7.Size = new System.Drawing.Size(122, 47);
			this.groupBox7.TabIndex = 28;
			this.groupBox7.TabStop = false;
			this.groupBox7.Text = "VALIDATE AXIS";
			// 
			// _chkEnableAxisA
			// 
			this._chkEnableAxisA.AutoSize = true;
			this._chkEnableAxisA.Location = new System.Drawing.Point(6, 18);
			this._chkEnableAxisA.Name = "_chkEnableAxisA";
			this._chkEnableAxisA.Size = new System.Drawing.Size(32, 16);
			this._chkEnableAxisA.TabIndex = 6;
			this._chkEnableAxisA.Text = "A";
			this._chkEnableAxisA.UseVisualStyleBackColor = true;
			// 
			// _chkEnableAxisB
			// 
			this._chkEnableAxisB.AutoSize = true;
			this._chkEnableAxisB.Location = new System.Drawing.Point(44, 18);
			this._chkEnableAxisB.Name = "_chkEnableAxisB";
			this._chkEnableAxisB.Size = new System.Drawing.Size(32, 16);
			this._chkEnableAxisB.TabIndex = 7;
			this._chkEnableAxisB.Text = "B";
			this._chkEnableAxisB.UseVisualStyleBackColor = true;
			// 
			// _chkEnableAxisC
			// 
			this._chkEnableAxisC.AutoSize = true;
			this._chkEnableAxisC.Location = new System.Drawing.Point(82, 18);
			this._chkEnableAxisC.Name = "_chkEnableAxisC";
			this._chkEnableAxisC.Size = new System.Drawing.Size(32, 16);
			this._chkEnableAxisC.TabIndex = 8;
			this._chkEnableAxisC.Text = "C";
			this._chkEnableAxisC.UseVisualStyleBackColor = true;
			// 
			// _btnSet
			// 
			this._btnSet.Location = new System.Drawing.Point(74, 139);
			this._btnSet.Name = "_btnSet";
			this._btnSet.Size = new System.Drawing.Size(60, 30);
			this._btnSet.TabIndex = 5;
			this._btnSet.Text = "SET";
			this._btnSet.UseVisualStyleBackColor = true;
			this._btnSet.Click += new System.EventHandler(this._btnSet_Click);
			// 
			// _chkEnableEsf
			// 
			this._chkEnableEsf.AutoSize = true;
			this._chkEnableEsf.Location = new System.Drawing.Point(10, 18);
			this._chkEnableEsf.Name = "_chkEnableEsf";
			this._chkEnableEsf.Size = new System.Drawing.Size(101, 16);
			this._chkEnableEsf.TabIndex = 29;
			this._chkEnableEsf.Text = "ESF ENABLED";
			this._chkEnableEsf.UseVisualStyleBackColor = true;
			// 
			// _chkEnableGsf
			// 
			this._chkEnableGsf.AutoSize = true;
			this._chkEnableGsf.Location = new System.Drawing.Point(10, 40);
			this._chkEnableGsf.Name = "_chkEnableGsf";
			this._chkEnableGsf.Size = new System.Drawing.Size(102, 16);
			this._chkEnableGsf.TabIndex = 30;
			this._chkEnableGsf.Text = "GSF ENABLED";
			this._chkEnableGsf.UseVisualStyleBackColor = true;
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this._chkEnableEsf);
			this.groupBox1.Controls.Add(this._chkEnableGsf);
			this.groupBox1.Location = new System.Drawing.Point(8, 65);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(126, 68);
			this.groupBox1.TabIndex = 31;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "AEC";
			// 
			// FormStartupSetting
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(152, 177);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this.groupBox7);
			this.Controls.Add(this._btnSet);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
			this.Name = "FormStartupSetting";
			this.ShowInTaskbar = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Startup Setting";
			this.Load += new System.EventHandler(this.FormStartupSetting_Load);
			this.groupBox7.ResumeLayout(false);
			this.groupBox7.PerformLayout();
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.GroupBox groupBox7;
		private System.Windows.Forms.CheckBox _chkEnableAxisA;
		private System.Windows.Forms.CheckBox _chkEnableAxisB;
		private System.Windows.Forms.CheckBox _chkEnableAxisC;
		private System.Windows.Forms.Button _btnSet;
		private System.Windows.Forms.CheckBox _chkEnableEsf;
		private System.Windows.Forms.CheckBox _chkEnableGsf;
		private System.Windows.Forms.GroupBox groupBox1;
	}
}