// <auto-generated />
namespace DebugMcIf
{
	partial class FormProcessConditionTable
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
			this._dgCond = new System.Windows.Forms.DataGridView();
			this.Number = new System.Windows.Forms.DataGridViewButtonColumn();
			this.TurnOn = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.TurnOff = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Cap = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.ServoControl = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Crs = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.SfrFront = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.SfrBack = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Inverter = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.ServoSelect = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.PowerSupply = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Pol = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.JumpDown = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.JumpUp = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Material = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Diameter = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Ip = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Comment = new System.Windows.Forms.DataGridViewTextBoxColumn();
			((System.ComponentModel.ISupportInitialize)(this._dgCond)).BeginInit();
			this.SuspendLayout();
			// 
			// _dgCond
			// 
			this._dgCond.AllowUserToAddRows = false;
			this._dgCond.AllowUserToDeleteRows = false;
			this._dgCond.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this._dgCond.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Number,
            this.TurnOn,
            this.TurnOff,
            this.Cap,
            this.ServoControl,
            this.Crs,
            this.SfrFront,
            this.SfrBack,
            this.Inverter,
            this.ServoSelect,
            this.PowerSupply,
            this.Pol,
            this.JumpDown,
            this.JumpUp,
            this.Material,
            this.Diameter,
            this.Ip,
            this.Comment});
			dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
			dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
			dataGridViewCellStyle2.Font = new System.Drawing.Font("MS UI Gothic", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
			this._dgCond.DefaultCellStyle = dataGridViewCellStyle2;
			this._dgCond.Dock = System.Windows.Forms.DockStyle.Fill;
			this._dgCond.EditMode = System.Windows.Forms.DataGridViewEditMode.EditOnKeystroke;
			this._dgCond.Location = new System.Drawing.Point(0, 0);
			this._dgCond.MultiSelect = false;
			this._dgCond.Name = "_dgCond";
			this._dgCond.RowTemplate.Height = 21;
			this._dgCond.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.CellSelect;
			this._dgCond.Size = new System.Drawing.Size(624, 443);
			this._dgCond.TabIndex = 57;
			this._dgCond.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this._dgCond_CellClick);
			this._dgCond.CellEndEdit += new System.Windows.Forms.DataGridViewCellEventHandler(this._dgCond_CellEndEdit);
			this._dgCond.CellValidating += new System.Windows.Forms.DataGridViewCellValidatingEventHandler(this._dgCond_CellValidating);
			this._dgCond.CurrentCellChanged += new System.EventHandler(this._dgCond_CurrentCellChanged);
			// 
			// Number
			// 
			this.Number.HeaderText = "#";
			this.Number.MinimumWidth = 24;
			this.Number.Name = "Number";
			this.Number.ReadOnly = true;
			this.Number.Resizable = System.Windows.Forms.DataGridViewTriState.False;
			this.Number.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
			// 
			// TurnOn
			// 
			this.TurnOn.HeaderText = "TOn";
			this.TurnOn.Name = "TurnOn";
			// 
			// TurnOff
			// 
			this.TurnOff.HeaderText = "TOff";
			this.TurnOff.Name = "TurnOff";
			// 
			// Cap
			// 
			this.Cap.HeaderText = "CAP";
			this.Cap.Name = "Cap";
			// 
			// ServoControl
			// 
			this.ServoControl.HeaderText = "SC";
			this.ServoControl.Name = "ServoControl";
			// 
			// Crs
			// 
			this.Crs.HeaderText = "CRS";
			this.Crs.Name = "Crs";
			// 
			// SfrFront
			// 
			this.SfrFront.HeaderText = "SfrFr";
			this.SfrFront.Name = "SfrFront";
			// 
			// SfrBack
			// 
			this.SfrBack.HeaderText = "SfrBk";
			this.SfrBack.Name = "SfrBack";
			// 
			// Inverter
			// 
			this.Inverter.HeaderText = "Inv.";
			this.Inverter.Name = "Inverter";
			// 
			// ServoSelect
			// 
			this.ServoSelect.HeaderText = "Svo";
			this.ServoSelect.Name = "ServoSelect";
			// 
			// PowerSupply
			// 
			this.PowerSupply.HeaderText = "PS";
			this.PowerSupply.Name = "PowerSupply";
			// 
			// Pol
			// 
			this.Pol.HeaderText = "POL";
			this.Pol.Name = "Pol";
			// 
			// JumpDown
			// 
			this.JumpDown.HeaderText = "JmpDn";
			this.JumpDown.Name = "JumpDown";
			// 
			// JumpUp
			// 
			this.JumpUp.HeaderText = "JmpUp";
			this.JumpUp.Name = "JumpUp";
			// 
			// Material
			// 
			this.Material.HeaderText = "Mat.";
			this.Material.Name = "Material";
			// 
			// Diameter
			// 
			this.Diameter.HeaderText = "Dia.";
			this.Diameter.Name = "Diameter";
			// 
			// Ip
			// 
			this.Ip.HeaderText = "IP";
			this.Ip.Name = "Ip";
			// 
			// Comment
			// 
			dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			this.Comment.DefaultCellStyle = dataGridViewCellStyle1;
			this.Comment.HeaderText = "Comment";
			this.Comment.Name = "Comment";
			// 
			// FormProcessConditionTable
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(624, 443);
			this.Controls.Add(this._dgCond);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
			this.Name = "FormProcessConditionTable";
			this.Text = "ProcessConditionTable";
			this.Load += new System.EventHandler(this.FormProcessConditionTable_Load);
			((System.ComponentModel.ISupportInitialize)(this._dgCond)).EndInit();
			this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.DataGridView _dgCond;
		private System.Windows.Forms.DataGridViewButtonColumn Number;
		private System.Windows.Forms.DataGridViewTextBoxColumn TurnOn;
		private System.Windows.Forms.DataGridViewTextBoxColumn TurnOff;
		private System.Windows.Forms.DataGridViewTextBoxColumn Cap;
		private System.Windows.Forms.DataGridViewTextBoxColumn ServoControl;
		private System.Windows.Forms.DataGridViewTextBoxColumn Crs;
		private System.Windows.Forms.DataGridViewTextBoxColumn SfrFront;
		private System.Windows.Forms.DataGridViewTextBoxColumn SfrBack;
		private System.Windows.Forms.DataGridViewTextBoxColumn Inverter;
		private System.Windows.Forms.DataGridViewTextBoxColumn ServoSelect;
		private System.Windows.Forms.DataGridViewTextBoxColumn PowerSupply;
		private System.Windows.Forms.DataGridViewTextBoxColumn Pol;
		private System.Windows.Forms.DataGridViewTextBoxColumn JumpDown;
		private System.Windows.Forms.DataGridViewTextBoxColumn JumpUp;
		private System.Windows.Forms.DataGridViewTextBoxColumn Material;
		private System.Windows.Forms.DataGridViewTextBoxColumn Diameter;
		private System.Windows.Forms.DataGridViewTextBoxColumn Ip;
		private System.Windows.Forms.DataGridViewTextBoxColumn Comment;
	}
}