// <auto-generated />
namespace DebugMcIf
{
	partial class FormAec
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this._edtElectrodeInstallNumber = new System.Windows.Forms.NumericUpDown();
			this._grpElectrodeInstall = new System.Windows.Forms.GroupBox();
			this._btnElectrodeRemove = new System.Windows.Forms.Button();
			this.label1 = new System.Windows.Forms.Label();
			this._btnElectrodeInstall = new System.Windows.Forms.Button();
			this._grpElectrodeMove = new System.Windows.Forms.GroupBox();
			this._btnElectrodeStandBy = new System.Windows.Forms.Button();
			this._userAxisElectrode = new DebugMcIf.UserAxisFlags();
			this._btnElectrodeFoward = new System.Windows.Forms.Button();
			this._btnElectrodeExchange = new System.Windows.Forms.Button();
			this._grpEsfMagazineMove = new System.Windows.Forms.GroupBox();
			this._btnEsfMagazineIncliment = new System.Windows.Forms.Button();
			this.label2 = new System.Windows.Forms.Label();
			this._btnReqEsfMoveMagazine = new System.Windows.Forms.Button();
			this._edtEsfMagazineNumber = new System.Windows.Forms.NumericUpDown();
			this._grpEsfArmMove = new System.Windows.Forms.GroupBox();
			this._btnEsfArmBack = new System.Windows.Forms.Button();
			this._btnEsfArmMiddle = new System.Windows.Forms.Button();
			this._btnEsfArmFoward = new System.Windows.Forms.Button();
			this._grpEsfFinger = new System.Windows.Forms.GroupBox();
			this._btnEsfFingerClose = new System.Windows.Forms.Button();
			this._btnEsfFingerOpen = new System.Windows.Forms.Button();
			this._grpGuideMove = new System.Windows.Forms.GroupBox();
			this._btnGuideStandBy = new System.Windows.Forms.Button();
			this._userAxisGuide = new DebugMcIf.UserAxisFlags();
			this._btnGuideExchange = new System.Windows.Forms.Button();
			this._grpGuideInstall = new System.Windows.Forms.GroupBox();
			this._btnGuideRemove = new System.Windows.Forms.Button();
			this.label3 = new System.Windows.Forms.Label();
			this._btnGuideInstall = new System.Windows.Forms.Button();
			this._edtGuideInstallNumber = new System.Windows.Forms.NumericUpDown();
			this._grpGsfArmMove = new System.Windows.Forms.GroupBox();
			this._btnGsfArmBack = new System.Windows.Forms.Button();
			this._btnGsfArmFoward = new System.Windows.Forms.Button();
			((System.ComponentModel.ISupportInitialize)(this._edtElectrodeInstallNumber)).BeginInit();
			this._grpElectrodeInstall.SuspendLayout();
			this._grpElectrodeMove.SuspendLayout();
			this._grpEsfMagazineMove.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtEsfMagazineNumber)).BeginInit();
			this._grpEsfArmMove.SuspendLayout();
			this._grpEsfFinger.SuspendLayout();
			this._grpGuideMove.SuspendLayout();
			this._grpGuideInstall.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtGuideInstallNumber)).BeginInit();
			this._grpGsfArmMove.SuspendLayout();
			this.SuspendLayout();
			// 
			// _edtElectrodeInstallNumber
			// 
			this._edtElectrodeInstallNumber.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtElectrodeInstallNumber.ImeMode = System.Windows.Forms.ImeMode.Off;
			this._edtElectrodeInstallNumber.Location = new System.Drawing.Point(34, 18);
			this._edtElectrodeInstallNumber.Name = "_edtElectrodeInstallNumber";
			this._edtElectrodeInstallNumber.Size = new System.Drawing.Size(61, 31);
			this._edtElectrodeInstallNumber.TabIndex = 59;
			this._edtElectrodeInstallNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _grpElectrodeInstall
			// 
			this._grpElectrodeInstall.Controls.Add(this._btnElectrodeRemove);
			this._grpElectrodeInstall.Controls.Add(this.label1);
			this._grpElectrodeInstall.Controls.Add(this._btnElectrodeInstall);
			this._grpElectrodeInstall.Controls.Add(this._edtElectrodeInstallNumber);
			this._grpElectrodeInstall.Location = new System.Drawing.Point(12, 12);
			this._grpElectrodeInstall.Name = "_grpElectrodeInstall";
			this._grpElectrodeInstall.Size = new System.Drawing.Size(325, 57);
			this._grpElectrodeInstall.TabIndex = 62;
			this._grpElectrodeInstall.TabStop = false;
			this._grpElectrodeInstall.Text = "ELECTRODE INSTALL";
			// 
			// _btnElectrodeRemove
			// 
			this._btnElectrodeRemove.Location = new System.Drawing.Point(218, 18);
			this._btnElectrodeRemove.Name = "_btnElectrodeRemove";
			this._btnElectrodeRemove.Size = new System.Drawing.Size(100, 30);
			this._btnElectrodeRemove.TabIndex = 67;
			this._btnElectrodeRemove.Text = "REMOVE";
			this._btnElectrodeRemove.UseVisualStyleBackColor = true;
			this._btnElectrodeRemove.Click += new System.EventHandler(this._btnElectrodeInsall_Click);
			// 
			// label1
			// 
			this.label1.AutoSize = true;
			this.label1.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label1.Location = new System.Drawing.Point(6, 20);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(22, 24);
			this.label1.TabIndex = 62;
			this.label1.Text = "#";
			// 
			// _btnElectrodeInstall
			// 
			this._btnElectrodeInstall.Location = new System.Drawing.Point(112, 18);
			this._btnElectrodeInstall.Name = "_btnElectrodeInstall";
			this._btnElectrodeInstall.Size = new System.Drawing.Size(100, 30);
			this._btnElectrodeInstall.TabIndex = 67;
			this._btnElectrodeInstall.Text = "INSTALL";
			this._btnElectrodeInstall.UseVisualStyleBackColor = true;
			this._btnElectrodeInstall.Click += new System.EventHandler(this._btnElectrodeInsall_Click);
			// 
			// _grpElectrodeMove
			// 
			this._grpElectrodeMove.Controls.Add(this._btnElectrodeStandBy);
			this._grpElectrodeMove.Controls.Add(this._userAxisElectrode);
			this._grpElectrodeMove.Controls.Add(this._btnElectrodeFoward);
			this._grpElectrodeMove.Controls.Add(this._btnElectrodeExchange);
			this._grpElectrodeMove.Location = new System.Drawing.Point(12, 75);
			this._grpElectrodeMove.Name = "_grpElectrodeMove";
			this._grpElectrodeMove.Size = new System.Drawing.Size(325, 86);
			this._grpElectrodeMove.TabIndex = 63;
			this._grpElectrodeMove.TabStop = false;
			this._grpElectrodeMove.Text = "ELECTRODE MOVE";
			// 
			// _btnElectrodeStandBy
			// 
			this._btnElectrodeStandBy.Location = new System.Drawing.Point(218, 47);
			this._btnElectrodeStandBy.Name = "_btnElectrodeStandBy";
			this._btnElectrodeStandBy.Size = new System.Drawing.Size(100, 30);
			this._btnElectrodeStandBy.TabIndex = 67;
			this._btnElectrodeStandBy.Text = "STAND BY";
			this._btnElectrodeStandBy.UseVisualStyleBackColor = true;
			this._btnElectrodeStandBy.Click += new System.EventHandler(this._btnElectrodeMove_Click);
			// 
			// _userAxisElectrode
			// 
			this._userAxisElectrode.Location = new System.Drawing.Point(6, 18);
			this._userAxisElectrode.Name = "_userAxisElectrode";
			this._userAxisElectrode.Selected = ECNC3.Enumeration.AxisBits.Free;
			this._userAxisElectrode.Size = new System.Drawing.Size(243, 23);
			this._userAxisElectrode.TabIndex = 3;
			// 
			// _btnElectrodeFoward
			// 
			this._btnElectrodeFoward.Location = new System.Drawing.Point(112, 47);
			this._btnElectrodeFoward.Name = "_btnElectrodeFoward";
			this._btnElectrodeFoward.Size = new System.Drawing.Size(100, 30);
			this._btnElectrodeFoward.TabIndex = 67;
			this._btnElectrodeFoward.Text = "FOWARD";
			this._btnElectrodeFoward.UseVisualStyleBackColor = true;
			this._btnElectrodeFoward.Click += new System.EventHandler(this._btnElectrodeMove_Click);
			// 
			// _btnElectrodeExchange
			// 
			this._btnElectrodeExchange.Location = new System.Drawing.Point(6, 47);
			this._btnElectrodeExchange.Name = "_btnElectrodeExchange";
			this._btnElectrodeExchange.Size = new System.Drawing.Size(100, 30);
			this._btnElectrodeExchange.TabIndex = 67;
			this._btnElectrodeExchange.Text = "EXCHANGE";
			this._btnElectrodeExchange.UseVisualStyleBackColor = true;
			this._btnElectrodeExchange.Click += new System.EventHandler(this._btnElectrodeMove_Click);
			// 
			// _grpEsfMagazineMove
			// 
			this._grpEsfMagazineMove.Controls.Add(this._btnEsfMagazineIncliment);
			this._grpEsfMagazineMove.Controls.Add(this.label2);
			this._grpEsfMagazineMove.Controls.Add(this._btnReqEsfMoveMagazine);
			this._grpEsfMagazineMove.Controls.Add(this._edtEsfMagazineNumber);
			this._grpEsfMagazineMove.Location = new System.Drawing.Point(12, 167);
			this._grpEsfMagazineMove.Name = "_grpEsfMagazineMove";
			this._grpEsfMagazineMove.Size = new System.Drawing.Size(325, 58);
			this._grpEsfMagazineMove.TabIndex = 64;
			this._grpEsfMagazineMove.TabStop = false;
			this._grpEsfMagazineMove.Text = "ESF MAGAZINE MOVE";
			// 
			// _btnEsfMagazineIncliment
			// 
			this._btnEsfMagazineIncliment.Location = new System.Drawing.Point(6, 18);
			this._btnEsfMagazineIncliment.Name = "_btnEsfMagazineIncliment";
			this._btnEsfMagazineIncliment.Size = new System.Drawing.Size(100, 30);
			this._btnEsfMagazineIncliment.TabIndex = 67;
			this._btnEsfMagazineIncliment.Text = "INCLIMENT";
			this._btnEsfMagazineIncliment.UseVisualStyleBackColor = true;
			this._btnEsfMagazineIncliment.Click += new System.EventHandler(this._btnEsfMoveMagazine_Click);
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label2.Location = new System.Drawing.Point(108, 20);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(41, 24);
			this.label2.TabIndex = 62;
			this.label2.Text = "/ #";
			// 
			// _btnReqEsfMoveMagazine
			// 
			this._btnReqEsfMoveMagazine.Location = new System.Drawing.Point(218, 18);
			this._btnReqEsfMoveMagazine.Name = "_btnReqEsfMoveMagazine";
			this._btnReqEsfMoveMagazine.Size = new System.Drawing.Size(100, 30);
			this._btnReqEsfMoveMagazine.TabIndex = 0;
			this._btnReqEsfMoveMagazine.Text = "MOVE";
			this._btnReqEsfMoveMagazine.UseVisualStyleBackColor = true;
			this._btnReqEsfMoveMagazine.Click += new System.EventHandler(this._btnEsfMoveMagazine_Click);
			// 
			// _edtEsfMagazineNumber
			// 
			this._edtEsfMagazineNumber.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtEsfMagazineNumber.ImeMode = System.Windows.Forms.ImeMode.Off;
			this._edtEsfMagazineNumber.Location = new System.Drawing.Point(151, 18);
			this._edtEsfMagazineNumber.Name = "_edtEsfMagazineNumber";
			this._edtEsfMagazineNumber.Size = new System.Drawing.Size(61, 31);
			this._edtEsfMagazineNumber.TabIndex = 59;
			this._edtEsfMagazineNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _grpEsfArmMove
			// 
			this._grpEsfArmMove.Controls.Add(this._btnEsfArmBack);
			this._grpEsfArmMove.Controls.Add(this._btnEsfArmMiddle);
			this._grpEsfArmMove.Controls.Add(this._btnEsfArmFoward);
			this._grpEsfArmMove.Location = new System.Drawing.Point(12, 231);
			this._grpEsfArmMove.Name = "_grpEsfArmMove";
			this._grpEsfArmMove.Size = new System.Drawing.Size(325, 55);
			this._grpEsfArmMove.TabIndex = 65;
			this._grpEsfArmMove.TabStop = false;
			this._grpEsfArmMove.Text = "ESF ARM MOVE";
			// 
			// _btnEsfArmBack
			// 
			this._btnEsfArmBack.Location = new System.Drawing.Point(218, 18);
			this._btnEsfArmBack.Name = "_btnEsfArmBack";
			this._btnEsfArmBack.Size = new System.Drawing.Size(100, 30);
			this._btnEsfArmBack.TabIndex = 67;
			this._btnEsfArmBack.Text = "BACK";
			this._btnEsfArmBack.UseVisualStyleBackColor = true;
			this._btnEsfArmBack.Click += new System.EventHandler(this._btnEsfMoveArm_Click);
			// 
			// _btnEsfArmMiddle
			// 
			this._btnEsfArmMiddle.Location = new System.Drawing.Point(112, 18);
			this._btnEsfArmMiddle.Name = "_btnEsfArmMiddle";
			this._btnEsfArmMiddle.Size = new System.Drawing.Size(100, 30);
			this._btnEsfArmMiddle.TabIndex = 67;
			this._btnEsfArmMiddle.Text = "MIDDLE";
			this._btnEsfArmMiddle.UseVisualStyleBackColor = true;
			this._btnEsfArmMiddle.Click += new System.EventHandler(this._btnEsfMoveArm_Click);
			// 
			// _btnEsfArmFoward
			// 
			this._btnEsfArmFoward.Location = new System.Drawing.Point(6, 18);
			this._btnEsfArmFoward.Name = "_btnEsfArmFoward";
			this._btnEsfArmFoward.Size = new System.Drawing.Size(100, 30);
			this._btnEsfArmFoward.TabIndex = 67;
			this._btnEsfArmFoward.Text = "FOWARD";
			this._btnEsfArmFoward.UseVisualStyleBackColor = true;
			this._btnEsfArmFoward.Click += new System.EventHandler(this._btnEsfMoveArm_Click);
			// 
			// _grpEsfFinger
			// 
			this._grpEsfFinger.Controls.Add(this._btnEsfFingerClose);
			this._grpEsfFinger.Controls.Add(this._btnEsfFingerOpen);
			this._grpEsfFinger.Location = new System.Drawing.Point(12, 292);
			this._grpEsfFinger.Name = "_grpEsfFinger";
			this._grpEsfFinger.Size = new System.Drawing.Size(220, 55);
			this._grpEsfFinger.TabIndex = 66;
			this._grpEsfFinger.TabStop = false;
			this._grpEsfFinger.Text = "ESF FINGER";
			// 
			// _btnEsfFingerClose
			// 
			this._btnEsfFingerClose.Location = new System.Drawing.Point(112, 18);
			this._btnEsfFingerClose.Name = "_btnEsfFingerClose";
			this._btnEsfFingerClose.Size = new System.Drawing.Size(100, 30);
			this._btnEsfFingerClose.TabIndex = 1;
			this._btnEsfFingerClose.Text = "CLOSE";
			this._btnEsfFingerClose.UseVisualStyleBackColor = true;
			this._btnEsfFingerClose.Click += new System.EventHandler(this._btnEsfMoveFinger_Click);
			// 
			// _btnEsfFingerOpen
			// 
			this._btnEsfFingerOpen.Location = new System.Drawing.Point(6, 18);
			this._btnEsfFingerOpen.Name = "_btnEsfFingerOpen";
			this._btnEsfFingerOpen.Size = new System.Drawing.Size(100, 30);
			this._btnEsfFingerOpen.TabIndex = 0;
			this._btnEsfFingerOpen.Text = "OPEN";
			this._btnEsfFingerOpen.UseVisualStyleBackColor = true;
			this._btnEsfFingerOpen.Click += new System.EventHandler(this._btnEsfMoveFinger_Click);
			// 
			// _grpGuideMove
			// 
			this._grpGuideMove.Controls.Add(this._btnGuideStandBy);
			this._grpGuideMove.Controls.Add(this._userAxisGuide);
			this._grpGuideMove.Controls.Add(this._btnGuideExchange);
			this._grpGuideMove.Location = new System.Drawing.Point(346, 75);
			this._grpGuideMove.Name = "_grpGuideMove";
			this._grpGuideMove.Size = new System.Drawing.Size(325, 86);
			this._grpGuideMove.TabIndex = 67;
			this._grpGuideMove.TabStop = false;
			this._grpGuideMove.Text = "GUIDE MOVE";
			// 
			// _btnGuideStandBy
			// 
			this._btnGuideStandBy.Location = new System.Drawing.Point(218, 47);
			this._btnGuideStandBy.Name = "_btnGuideStandBy";
			this._btnGuideStandBy.Size = new System.Drawing.Size(100, 30);
			this._btnGuideStandBy.TabIndex = 67;
			this._btnGuideStandBy.Text = "STAND BY";
			this._btnGuideStandBy.UseVisualStyleBackColor = true;
			this._btnGuideStandBy.Click += new System.EventHandler(this._btnGuideMove_Click);
			// 
			// _userAxisGuide
			// 
			this._userAxisGuide.Location = new System.Drawing.Point(6, 18);
			this._userAxisGuide.Name = "_userAxisGuide";
			this._userAxisGuide.Selected = ECNC3.Enumeration.AxisBits.Free;
			this._userAxisGuide.Size = new System.Drawing.Size(243, 23);
			this._userAxisGuide.TabIndex = 3;
			// 
			// _btnGuideExchange
			// 
			this._btnGuideExchange.Location = new System.Drawing.Point(6, 47);
			this._btnGuideExchange.Name = "_btnGuideExchange";
			this._btnGuideExchange.Size = new System.Drawing.Size(100, 30);
			this._btnGuideExchange.TabIndex = 67;
			this._btnGuideExchange.Text = "EXCHANGE";
			this._btnGuideExchange.UseVisualStyleBackColor = true;
			this._btnGuideExchange.Click += new System.EventHandler(this._btnGuideMove_Click);
			// 
			// _grpGuideInstall
			// 
			this._grpGuideInstall.Controls.Add(this._btnGuideRemove);
			this._grpGuideInstall.Controls.Add(this.label3);
			this._grpGuideInstall.Controls.Add(this._btnGuideInstall);
			this._grpGuideInstall.Controls.Add(this._edtGuideInstallNumber);
			this._grpGuideInstall.Location = new System.Drawing.Point(346, 12);
			this._grpGuideInstall.Name = "_grpGuideInstall";
			this._grpGuideInstall.Size = new System.Drawing.Size(325, 57);
			this._grpGuideInstall.TabIndex = 68;
			this._grpGuideInstall.TabStop = false;
			this._grpGuideInstall.Text = "GUIDE INSTALL";
			// 
			// _btnGuideRemove
			// 
			this._btnGuideRemove.Location = new System.Drawing.Point(218, 18);
			this._btnGuideRemove.Name = "_btnGuideRemove";
			this._btnGuideRemove.Size = new System.Drawing.Size(100, 30);
			this._btnGuideRemove.TabIndex = 70;
			this._btnGuideRemove.Text = "REMOVE";
			this._btnGuideRemove.UseVisualStyleBackColor = true;
			// 
			// label3
			// 
			this.label3.AutoSize = true;
			this.label3.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label3.Location = new System.Drawing.Point(6, 20);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(22, 24);
			this.label3.TabIndex = 69;
			this.label3.Text = "#";
			// 
			// _btnGuideInstall
			// 
			this._btnGuideInstall.Location = new System.Drawing.Point(112, 18);
			this._btnGuideInstall.Name = "_btnGuideInstall";
			this._btnGuideInstall.Size = new System.Drawing.Size(100, 30);
			this._btnGuideInstall.TabIndex = 71;
			this._btnGuideInstall.Text = "INSTALL";
			this._btnGuideInstall.UseVisualStyleBackColor = true;
			this._btnGuideInstall.Click += new System.EventHandler(this._btnGuideInstall_Click);
			// 
			// _edtGuideInstallNumber
			// 
			this._edtGuideInstallNumber.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtGuideInstallNumber.ImeMode = System.Windows.Forms.ImeMode.Off;
			this._edtGuideInstallNumber.Location = new System.Drawing.Point(34, 18);
			this._edtGuideInstallNumber.Name = "_edtGuideInstallNumber";
			this._edtGuideInstallNumber.Size = new System.Drawing.Size(61, 31);
			this._edtGuideInstallNumber.TabIndex = 68;
			this._edtGuideInstallNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// _grpGsfArmMove
			// 
			this._grpGsfArmMove.Controls.Add(this._btnGsfArmBack);
			this._grpGsfArmMove.Controls.Add(this._btnGsfArmFoward);
			this._grpGsfArmMove.Location = new System.Drawing.Point(346, 231);
			this._grpGsfArmMove.Name = "_grpGsfArmMove";
			this._grpGsfArmMove.Size = new System.Drawing.Size(325, 55);
			this._grpGsfArmMove.TabIndex = 69;
			this._grpGsfArmMove.TabStop = false;
			this._grpGsfArmMove.Text = "GSF ARM MOVE";
			// 
			// _btnGsfArmBack
			// 
			this._btnGsfArmBack.Location = new System.Drawing.Point(218, 18);
			this._btnGsfArmBack.Name = "_btnGsfArmBack";
			this._btnGsfArmBack.Size = new System.Drawing.Size(100, 30);
			this._btnGsfArmBack.TabIndex = 68;
			this._btnGsfArmBack.Text = "BACK";
			this._btnGsfArmBack.UseVisualStyleBackColor = true;
			this._btnGsfArmBack.Click += new System.EventHandler(this._btnGsfMoveArm_Click);
			// 
			// _btnGsfArmFoward
			// 
			this._btnGsfArmFoward.Location = new System.Drawing.Point(6, 18);
			this._btnGsfArmFoward.Name = "_btnGsfArmFoward";
			this._btnGsfArmFoward.Size = new System.Drawing.Size(100, 30);
			this._btnGsfArmFoward.TabIndex = 69;
			this._btnGsfArmFoward.Text = "FOWARD";
			this._btnGsfArmFoward.UseVisualStyleBackColor = true;
			this._btnGsfArmFoward.Click += new System.EventHandler(this._btnGsfMoveArm_Click);
			// 
			// FormAec
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(683, 352);
			this.Controls.Add(this._grpGsfArmMove);
			this.Controls.Add(this._grpGuideInstall);
			this.Controls.Add(this._grpGuideMove);
			this.Controls.Add(this._grpEsfFinger);
			this.Controls.Add(this._grpEsfArmMove);
			this.Controls.Add(this._grpEsfMagazineMove);
			this.Controls.Add(this._grpElectrodeMove);
			this.Controls.Add(this._grpElectrodeInstall);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
			this.Name = "FormAec";
			this.Text = "AEC";
			this.Load += new System.EventHandler(this.FormAec_Load);
			((System.ComponentModel.ISupportInitialize)(this._edtElectrodeInstallNumber)).EndInit();
			this._grpElectrodeInstall.ResumeLayout(false);
			this._grpElectrodeInstall.PerformLayout();
			this._grpElectrodeMove.ResumeLayout(false);
			this._grpEsfMagazineMove.ResumeLayout(false);
			this._grpEsfMagazineMove.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtEsfMagazineNumber)).EndInit();
			this._grpEsfArmMove.ResumeLayout(false);
			this._grpEsfFinger.ResumeLayout(false);
			this._grpGuideMove.ResumeLayout(false);
			this._grpGuideInstall.ResumeLayout(false);
			this._grpGuideInstall.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtGuideInstallNumber)).EndInit();
			this._grpGsfArmMove.ResumeLayout(false);
			this.ResumeLayout(false);

		}

		#endregion
		private System.Windows.Forms.NumericUpDown _edtElectrodeInstallNumber;
		private System.Windows.Forms.GroupBox _grpElectrodeInstall;
		private System.Windows.Forms.GroupBox _grpElectrodeMove;
		private UserAxisFlags _userAxisElectrode;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.GroupBox _grpEsfMagazineMove;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.Button _btnReqEsfMoveMagazine;
		private System.Windows.Forms.NumericUpDown _edtEsfMagazineNumber;
		private System.Windows.Forms.GroupBox _grpEsfArmMove;
		private System.Windows.Forms.GroupBox _grpEsfFinger;
		private System.Windows.Forms.Button _btnEsfFingerClose;
		private System.Windows.Forms.Button _btnEsfFingerOpen;
		private System.Windows.Forms.Button _btnEsfArmFoward;
		private System.Windows.Forms.Button _btnEsfArmMiddle;
		private System.Windows.Forms.Button _btnEsfArmBack;
		private System.Windows.Forms.Button _btnEsfMagazineIncliment;
		private System.Windows.Forms.Button _btnElectrodeExchange;
		private System.Windows.Forms.Button _btnElectrodeFoward;
		private System.Windows.Forms.Button _btnElectrodeStandBy;
		private System.Windows.Forms.Button _btnElectrodeInstall;
		private System.Windows.Forms.Button _btnElectrodeRemove;
		private System.Windows.Forms.GroupBox _grpGuideMove;
		private System.Windows.Forms.GroupBox _grpGuideInstall;
		private System.Windows.Forms.GroupBox _grpGsfArmMove;
		private System.Windows.Forms.Button _btnGuideRemove;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.Button _btnGuideInstall;
		private System.Windows.Forms.NumericUpDown _edtGuideInstallNumber;
		private System.Windows.Forms.Button _btnGuideStandBy;
		private System.Windows.Forms.Button _btnGuideExchange;
		private UserAxisFlags _userAxisGuide;
		private System.Windows.Forms.Button _btnGsfArmBack;
		private System.Windows.Forms.Button _btnGsfArmFoward;
	}
}