// <auto-generated />
namespace DebugMcIf
{
	partial class FormAxisMoving
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
			this._btnSet = new System.Windows.Forms.Button();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this._rdoTypeWork = new System.Windows.Forms.RadioButton();
			this._rdoTypeMachine = new System.Windows.Forms.RadioButton();
			this.groupBox2 = new System.Windows.Forms.GroupBox();
			this._rdoModeLiner = new System.Windows.Forms.RadioButton();
			this._rdoModeRetractToPtp = new System.Windows.Forms.RadioButton();
			this._rdoModePtp = new System.Windows.Forms.RadioButton();
			this._edtFeed = new System.Windows.Forms.NumericUpDown();
			this.label9 = new System.Windows.Forms.Label();
			this._rdoMoving = new System.Windows.Forms.RadioButton();
			this._rdoWorkOrigin = new System.Windows.Forms.RadioButton();
			this._dgPos = new System.Windows.Forms.DataGridView();
			this.Number = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.AxisX = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.AxisY = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.AxisW = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.AxisZ = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.AxisA = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.AxisB = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.AxisC = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.AxisI = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.NoUse = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this._userCoord = new DebugMcIf.UserCoordinate();
			this._rdoVirPos = new System.Windows.Forms.RadioButton();
			this.groupBox1.SuspendLayout();
			this.groupBox2.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtFeed)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._dgPos)).BeginInit();
			this.SuspendLayout();
			// 
			// _btnSet
			// 
			this._btnSet.Location = new System.Drawing.Point(170, 521);
			this._btnSet.Name = "_btnSet";
			this._btnSet.Size = new System.Drawing.Size(60, 30);
			this._btnSet.TabIndex = 32;
			this._btnSet.Text = "SET";
			this._btnSet.UseVisualStyleBackColor = true;
			this._btnSet.Click += new System.EventHandler(this._btnSet_Click);
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this._rdoTypeWork);
			this.groupBox1.Controls.Add(this._rdoTypeMachine);
			this.groupBox1.Location = new System.Drawing.Point(85, 12);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(126, 66);
			this.groupBox1.TabIndex = 33;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "COORD TYPE";
			// 
			// _rdoTypeWork
			// 
			this._rdoTypeWork.AutoSize = true;
			this._rdoTypeWork.Location = new System.Drawing.Point(6, 40);
			this._rdoTypeWork.Name = "_rdoTypeWork";
			this._rdoTypeWork.Size = new System.Drawing.Size(55, 16);
			this._rdoTypeWork.TabIndex = 1;
			this._rdoTypeWork.Text = "WORK";
			this._rdoTypeWork.UseVisualStyleBackColor = true;
			// 
			// _rdoTypeMachine
			// 
			this._rdoTypeMachine.AutoSize = true;
			this._rdoTypeMachine.Checked = true;
			this._rdoTypeMachine.Location = new System.Drawing.Point(6, 18);
			this._rdoTypeMachine.Name = "_rdoTypeMachine";
			this._rdoTypeMachine.Size = new System.Drawing.Size(74, 16);
			this._rdoTypeMachine.TabIndex = 0;
			this._rdoTypeMachine.TabStop = true;
			this._rdoTypeMachine.Text = "MACHINE";
			this._rdoTypeMachine.UseVisualStyleBackColor = true;
			// 
			// groupBox2
			// 
			this.groupBox2.Controls.Add(this._rdoModeLiner);
			this.groupBox2.Controls.Add(this._rdoModeRetractToPtp);
			this.groupBox2.Controls.Add(this._rdoModePtp);
			this.groupBox2.Location = new System.Drawing.Point(85, 84);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new System.Drawing.Size(126, 87);
			this.groupBox2.TabIndex = 34;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "MODE";
			// 
			// _rdoModeLiner
			// 
			this._rdoModeLiner.AutoSize = true;
			this._rdoModeLiner.Location = new System.Drawing.Point(6, 62);
			this._rdoModeLiner.Name = "_rdoModeLiner";
			this._rdoModeLiner.Size = new System.Drawing.Size(55, 16);
			this._rdoModeLiner.TabIndex = 3;
			this._rdoModeLiner.Text = "LINER";
			this._rdoModeLiner.UseVisualStyleBackColor = true;
			// 
			// _rdoModeRetractToPtp
			// 
			this._rdoModeRetractToPtp.AutoSize = true;
			this._rdoModeRetractToPtp.Location = new System.Drawing.Point(6, 40);
			this._rdoModeRetractToPtp.Name = "_rdoModeRetractToPtp";
			this._rdoModeRetractToPtp.Size = new System.Drawing.Size(120, 16);
			this._rdoModeRetractToPtp.TabIndex = 2;
			this._rdoModeRetractToPtp.Text = "RETRACT TO PTP";
			this._rdoModeRetractToPtp.UseVisualStyleBackColor = true;
			// 
			// _rdoModePtp
			// 
			this._rdoModePtp.AutoSize = true;
			this._rdoModePtp.Checked = true;
			this._rdoModePtp.Location = new System.Drawing.Point(6, 18);
			this._rdoModePtp.Name = "_rdoModePtp";
			this._rdoModePtp.Size = new System.Drawing.Size(44, 16);
			this._rdoModePtp.TabIndex = 2;
			this._rdoModePtp.TabStop = true;
			this._rdoModePtp.Text = "PTP";
			this._rdoModePtp.UseVisualStyleBackColor = true;
			// 
			// _edtFeed
			// 
			this._edtFeed.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtFeed.Location = new System.Drawing.Point(236, 305);
			this._edtFeed.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtFeed.Name = "_edtFeed";
			this._edtFeed.Size = new System.Drawing.Size(156, 31);
			this._edtFeed.TabIndex = 49;
			this._edtFeed.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label9
			// 
			this.label9.AutoSize = true;
			this.label9.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label9.Location = new System.Drawing.Point(166, 307);
			this.label9.Name = "label9";
			this.label9.Size = new System.Drawing.Size(59, 24);
			this.label9.TabIndex = 52;
			this.label9.Text = "Feed";
			// 
			// _rdoMoving
			// 
			this._rdoMoving.AutoSize = true;
			this._rdoMoving.Checked = true;
			this._rdoMoving.Location = new System.Drawing.Point(12, 12);
			this._rdoMoving.Name = "_rdoMoving";
			this._rdoMoving.Size = new System.Drawing.Size(67, 16);
			this._rdoMoving.TabIndex = 54;
			this._rdoMoving.TabStop = true;
			this._rdoMoving.Text = "MOVING";
			this._rdoMoving.UseVisualStyleBackColor = true;
			this._rdoMoving.CheckedChanged += new System.EventHandler(this._rdoMoving_CheckedChanged);
			// 
			// _rdoWorkOrigin
			// 
			this._rdoWorkOrigin.AutoSize = true;
			this._rdoWorkOrigin.Location = new System.Drawing.Point(12, 177);
			this._rdoWorkOrigin.Name = "_rdoWorkOrigin";
			this._rdoWorkOrigin.Size = new System.Drawing.Size(126, 16);
			this._rdoWorkOrigin.TabIndex = 55;
			this._rdoWorkOrigin.Text = "EDIT WORK ORIGIN";
			this._rdoWorkOrigin.UseVisualStyleBackColor = true;
			this._rdoWorkOrigin.CheckedChanged += new System.EventHandler(this._rdoWorkOrigin_CheckedChanged);
			// 
			// _dgPos
			// 
			this._dgPos.AllowUserToAddRows = false;
			this._dgPos.AllowUserToDeleteRows = false;
			this._dgPos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this._dgPos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Number,
            this.AxisX,
            this.AxisY,
            this.AxisW,
            this.AxisZ,
            this.AxisA,
            this.AxisB,
            this.AxisC,
            this.AxisI,
            this.NoUse});
			dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
			dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Window;
			dataGridViewCellStyle1.Font = new System.Drawing.Font("MS UI Gothic", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
			this._dgPos.DefaultCellStyle = dataGridViewCellStyle1;
			this._dgPos.Location = new System.Drawing.Point(252, 12);
			this._dgPos.MultiSelect = false;
			this._dgPos.Name = "_dgPos";
			this._dgPos.RowTemplate.Height = 21;
			this._dgPos.Size = new System.Drawing.Size(520, 509);
			this._dgPos.TabIndex = 56;
			this._dgPos.CurrentCellChanged += new System.EventHandler(this._dgPos_CurrentCellChanged);
			// 
			// Number
			// 
			this.Number.HeaderText = "#";
			this.Number.Name = "Number";
			// 
			// AxisX
			// 
			this.AxisX.HeaderText = "X";
			this.AxisX.Name = "AxisX";
			// 
			// AxisY
			// 
			this.AxisY.HeaderText = "Y";
			this.AxisY.Name = "AxisY";
			// 
			// AxisW
			// 
			this.AxisW.HeaderText = "W";
			this.AxisW.Name = "AxisW";
			// 
			// AxisZ
			// 
			this.AxisZ.HeaderText = "Z";
			this.AxisZ.Name = "AxisZ";
			// 
			// AxisA
			// 
			this.AxisA.HeaderText = "A";
			this.AxisA.Name = "AxisA";
			// 
			// AxisB
			// 
			this.AxisB.HeaderText = "B";
			this.AxisB.Name = "AxisB";
			// 
			// AxisC
			// 
			this.AxisC.HeaderText = "C";
			this.AxisC.Name = "AxisC";
			// 
			// AxisI
			// 
			this.AxisI.HeaderText = "I";
			this.AxisI.Name = "AxisI";
			// 
			// NoUse
			// 
			this.NoUse.HeaderText = "-";
			this.NoUse.Name = "NoUse";
			// 
			// _userCoord
			// 
			this._userCoord.Location = new System.Drawing.Point(12, 221);
			this._userCoord.Name = "_userCoord";
			this._userCoord.Size = new System.Drawing.Size(234, 300);
			this._userCoord.TabIndex = 53;
			// 
			// _rdoVirPos
			// 
			this._rdoVirPos.AutoSize = true;
			this._rdoVirPos.Location = new System.Drawing.Point(12, 199);
			this._rdoVirPos.Name = "_rdoVirPos";
			this._rdoVirPos.Size = new System.Drawing.Size(155, 16);
			this._rdoVirPos.TabIndex = 57;
			this._rdoVirPos.TabStop = true;
			this._rdoVirPos.Text = "EDIT VIRTUAL POSITION";
			this._rdoVirPos.UseVisualStyleBackColor = true;
			// 
			// FormAxisMoving
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(784, 563);
			this.Controls.Add(this._rdoVirPos);
			this.Controls.Add(this._dgPos);
			this.Controls.Add(this._rdoWorkOrigin);
			this.Controls.Add(this._rdoMoving);
			this.Controls.Add(this._userCoord);
			this.Controls.Add(this.label9);
			this.Controls.Add(this._edtFeed);
			this.Controls.Add(this.groupBox2);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this._btnSet);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
			this.Name = "FormAxisMoving";
			this.ShowInTaskbar = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Axis Moving";
			this.Load += new System.EventHandler(this.FormAxisMoving_Load);
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.groupBox2.ResumeLayout(false);
			this.groupBox2.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtFeed)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._dgPos)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Button _btnSet;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.RadioButton _rdoTypeWork;
		private System.Windows.Forms.RadioButton _rdoTypeMachine;
		private System.Windows.Forms.GroupBox groupBox2;
		private System.Windows.Forms.RadioButton _rdoModeLiner;
		private System.Windows.Forms.RadioButton _rdoModeRetractToPtp;
		private System.Windows.Forms.RadioButton _rdoModePtp;
		private System.Windows.Forms.NumericUpDown _edtFeed;
		private System.Windows.Forms.Label label9;
		private UserCoordinate _userCoord;
		private System.Windows.Forms.RadioButton _rdoMoving;
		private System.Windows.Forms.RadioButton _rdoWorkOrigin;
		private System.Windows.Forms.DataGridView _dgPos;
		private System.Windows.Forms.DataGridViewTextBoxColumn Number;
		private System.Windows.Forms.DataGridViewTextBoxColumn AxisX;
		private System.Windows.Forms.DataGridViewTextBoxColumn AxisY;
		private System.Windows.Forms.DataGridViewTextBoxColumn AxisW;
		private System.Windows.Forms.DataGridViewTextBoxColumn AxisZ;
		private System.Windows.Forms.DataGridViewTextBoxColumn AxisA;
		private System.Windows.Forms.DataGridViewTextBoxColumn AxisB;
		private System.Windows.Forms.DataGridViewTextBoxColumn AxisC;
		private System.Windows.Forms.DataGridViewTextBoxColumn AxisI;
		private System.Windows.Forms.DataGridViewTextBoxColumn NoUse;
		private System.Windows.Forms.RadioButton _rdoVirPos;
	}
}