// <auto-generated />
namespace DebugMcIf
{
	partial class FormProgram
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this._btnStart = new System.Windows.Forms.Button();
			this._btnResume = new System.Windows.Forms.Button();
			this._btnOpen = new System.Windows.Forms.Button();
			this._stcResult = new System.Windows.Forms.Label();
			this._stcErrorCode = new System.Windows.Forms.Label();
			this._stcErrorLine = new System.Windows.Forms.Label();
			this._lnkFilePath = new System.Windows.Forms.LinkLabel();
			this.label1 = new System.Windows.Forms.Label();
			this.label2 = new System.Windows.Forms.Label();
			this.label3 = new System.Windows.Forms.Label();
			this._edtProgram = new System.Windows.Forms.TextBox();
			this.panel1 = new System.Windows.Forms.Panel();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this._edtBlockNumber = new System.Windows.Forms.NumericUpDown();
			this.label4 = new System.Windows.Forms.Label();
			this._btnRead = new System.Windows.Forms.Button();
			this._chkSelectNNumber = new System.Windows.Forms.CheckBox();
			this.label5 = new System.Windows.Forms.Label();
			this._edtProgramNumber = new System.Windows.Forms.NumericUpDown();
			this.panel2 = new System.Windows.Forms.Panel();
			this.panel1.SuspendLayout();
			this.groupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtBlockNumber)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtProgramNumber)).BeginInit();
			this.panel2.SuspendLayout();
			this.SuspendLayout();
			// 
			// _btnStart
			// 
			this._btnStart.Location = new System.Drawing.Point(478, 56);
			this._btnStart.Name = "_btnStart";
			this._btnStart.Size = new System.Drawing.Size(75, 30);
			this._btnStart.TabIndex = 0;
			this._btnStart.Text = "START";
			this._btnStart.UseVisualStyleBackColor = true;
			this._btnStart.Click += new System.EventHandler(this._btnStart_Click);
			// 
			// _btnResume
			// 
			this._btnResume.Location = new System.Drawing.Point(397, 56);
			this._btnResume.Name = "_btnResume";
			this._btnResume.Size = new System.Drawing.Size(75, 30);
			this._btnResume.TabIndex = 1;
			this._btnResume.Text = "RESUME";
			this._btnResume.UseVisualStyleBackColor = true;
			this._btnResume.Click += new System.EventHandler(this._btnResume_Click);
			// 
			// _btnOpen
			// 
			this._btnOpen.Location = new System.Drawing.Point(119, 14);
			this._btnOpen.Name = "_btnOpen";
			this._btnOpen.Size = new System.Drawing.Size(75, 30);
			this._btnOpen.TabIndex = 2;
			this._btnOpen.Text = "OPEN";
			this._btnOpen.UseVisualStyleBackColor = true;
			this._btnOpen.Click += new System.EventHandler(this._btnOpen_Click);
			// 
			// _stcResult
			// 
			this._stcResult.AutoSize = true;
			this._stcResult.Location = new System.Drawing.Point(92, 59);
			this._stcResult.Name = "_stcResult";
			this._stcResult.Size = new System.Drawing.Size(48, 12);
			this._stcResult.TabIndex = 3;
			this._stcResult.Text = "RESULT";
			// 
			// _stcErrorCode
			// 
			this._stcErrorCode.AutoSize = true;
			this._stcErrorCode.Location = new System.Drawing.Point(92, 71);
			this._stcErrorCode.Name = "_stcErrorCode";
			this._stcErrorCode.Size = new System.Drawing.Size(79, 12);
			this._stcErrorCode.TabIndex = 4;
			this._stcErrorCode.Text = "ERROR CODE";
			// 
			// _stcErrorLine
			// 
			this._stcErrorLine.AutoSize = true;
			this._stcErrorLine.Location = new System.Drawing.Point(92, 83);
			this._stcErrorLine.Name = "_stcErrorLine";
			this._stcErrorLine.Size = new System.Drawing.Size(29, 12);
			this._stcErrorLine.TabIndex = 5;
			this._stcErrorLine.Text = "LINE";
			// 
			// _lnkFilePath
			// 
			this._lnkFilePath.AutoSize = true;
			this._lnkFilePath.Location = new System.Drawing.Point(7, 47);
			this._lnkFilePath.Name = "_lnkFilePath";
			this._lnkFilePath.Size = new System.Drawing.Size(62, 12);
			this._lnkFilePath.TabIndex = 6;
			this._lnkFilePath.TabStop = true;
			this._lnkFilePath.Text = "FILE PATH";
			// 
			// label1
			// 
			this.label1.AutoSize = true;
			this.label1.Location = new System.Drawing.Point(7, 83);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(29, 12);
			this.label1.TabIndex = 9;
			this.label1.Text = "LINE";
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Location = new System.Drawing.Point(7, 71);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(79, 12);
			this.label2.TabIndex = 8;
			this.label2.Text = "ERROR CODE";
			// 
			// label3
			// 
			this.label3.AutoSize = true;
			this.label3.Location = new System.Drawing.Point(7, 59);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(48, 12);
			this.label3.TabIndex = 7;
			this.label3.Text = "RESULT";
			// 
			// _edtProgram
			// 
			this._edtProgram.Dock = System.Windows.Forms.DockStyle.Fill;
			this._edtProgram.Location = new System.Drawing.Point(0, 0);
			this._edtProgram.Multiline = true;
			this._edtProgram.Name = "_edtProgram";
			this._edtProgram.Size = new System.Drawing.Size(582, 241);
			this._edtProgram.TabIndex = 10;
			// 
			// panel1
			// 
			this.panel1.Controls.Add(this.groupBox1);
			this.panel1.Controls.Add(this._btnRead);
			this.panel1.Controls.Add(this._chkSelectNNumber);
			this.panel1.Controls.Add(this.label5);
			this.panel1.Controls.Add(this._edtProgramNumber);
			this.panel1.Controls.Add(this._btnStart);
			this.panel1.Controls.Add(this._btnResume);
			this.panel1.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.panel1.Location = new System.Drawing.Point(0, 241);
			this.panel1.Name = "panel1";
			this.panel1.Size = new System.Drawing.Size(582, 112);
			this.panel1.TabIndex = 11;
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this._edtBlockNumber);
			this.groupBox1.Controls.Add(this.label4);
			this.groupBox1.Controls.Add(this._btnOpen);
			this.groupBox1.Controls.Add(this._stcErrorCode);
			this.groupBox1.Controls.Add(this.label1);
			this.groupBox1.Controls.Add(this._stcResult);
			this.groupBox1.Controls.Add(this.label2);
			this.groupBox1.Controls.Add(this.label3);
			this.groupBox1.Controls.Add(this._lnkFilePath);
			this.groupBox1.Controls.Add(this._stcErrorLine);
			this.groupBox1.Location = new System.Drawing.Point(3, 6);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(334, 100);
			this.groupBox1.TabIndex = 63;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "LOAD";
			// 
			// _edtBlockNumber
			// 
			this._edtBlockNumber.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtBlockNumber.Location = new System.Drawing.Point(60, 13);
			this._edtBlockNumber.Name = "_edtBlockNumber";
			this._edtBlockNumber.Size = new System.Drawing.Size(53, 31);
			this._edtBlockNumber.TabIndex = 59;
			this._edtBlockNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label4
			// 
			this.label4.AutoSize = true;
			this.label4.Location = new System.Drawing.Point(6, 26);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(48, 12);
			this.label4.TabIndex = 60;
			this.label4.Text = "BLOCK#";
			// 
			// _btnRead
			// 
			this._btnRead.Location = new System.Drawing.Point(478, 20);
			this._btnRead.Name = "_btnRead";
			this._btnRead.Size = new System.Drawing.Size(75, 30);
			this._btnRead.TabIndex = 62;
			this._btnRead.Text = "READ";
			this._btnRead.UseVisualStyleBackColor = true;
			this._btnRead.Click += new System.EventHandler(this._btnRead_Click);
			// 
			// _chkSelectNNumber
			// 
			this._chkSelectNNumber.AutoSize = true;
			this._chkSelectNNumber.Location = new System.Drawing.Point(353, 64);
			this._chkSelectNNumber.Name = "_chkSelectNNumber";
			this._chkSelectNNumber.Size = new System.Drawing.Size(38, 16);
			this._chkSelectNNumber.TabIndex = 61;
			this._chkSelectNNumber.Text = "N#";
			this._chkSelectNNumber.UseVisualStyleBackColor = true;
			// 
			// label5
			// 
			this.label5.AutoSize = true;
			this.label5.Location = new System.Drawing.Point(348, 29);
			this.label5.Name = "label5";
			this.label5.Size = new System.Drawing.Size(67, 12);
			this.label5.TabIndex = 60;
			this.label5.Text = "PROGRAM#";
			// 
			// _edtProgramNumber
			// 
			this._edtProgramNumber.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtProgramNumber.Location = new System.Drawing.Point(421, 19);
			this._edtProgramNumber.Name = "_edtProgramNumber";
			this._edtProgramNumber.Size = new System.Drawing.Size(53, 31);
			this._edtProgramNumber.TabIndex = 59;
			this._edtProgramNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this._edtProgramNumber.ValueChanged += new System.EventHandler(this._edtProgramNumber_ValueChanged);
			// 
			// panel2
			// 
			this.panel2.Controls.Add(this._edtProgram);
			this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel2.Location = new System.Drawing.Point(0, 0);
			this.panel2.Name = "panel2";
			this.panel2.Size = new System.Drawing.Size(582, 241);
			this.panel2.TabIndex = 12;
			// 
			// FormProgram
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(582, 353);
			this.Controls.Add(this.panel2);
			this.Controls.Add(this.panel1);
			this.Name = "FormProgram";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "FormProgram";
			this.panel1.ResumeLayout(false);
			this.panel1.PerformLayout();
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this._edtBlockNumber)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtProgramNumber)).EndInit();
			this.panel2.ResumeLayout(false);
			this.panel2.PerformLayout();
			this.ResumeLayout(false);

		}

		#endregion

		private System.Windows.Forms.Button _btnStart;
		private System.Windows.Forms.Button _btnResume;
		private System.Windows.Forms.Button _btnOpen;
		private System.Windows.Forms.Label _stcResult;
		private System.Windows.Forms.Label _stcErrorCode;
		private System.Windows.Forms.Label _stcErrorLine;
		private System.Windows.Forms.LinkLabel _lnkFilePath;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.TextBox _edtProgram;
		private System.Windows.Forms.Panel panel1;
		private System.Windows.Forms.Panel panel2;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.NumericUpDown _edtBlockNumber;
		private System.Windows.Forms.CheckBox _chkSelectNNumber;
		private System.Windows.Forms.Button _btnRead;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.NumericUpDown _edtProgramNumber;
	}
}