// <auto-generated />
namespace DebugMcIf
{
	partial class UserCoordinate
	{
		/// <summary> 
		/// 必要なデザイナー変数です。
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// 使用中のリソースをすべてクリーンアップします。
		/// </summary>
		/// <param name="disposing">マネージ リソースを破棄する場合は true を指定し、その他の場合は false を指定します。</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region コンポーネント デザイナーで生成されたコード

		/// <summary> 
		/// デザイナー サポートに必要なメソッドです。このメソッドの内容を 
		/// コード エディターで変更しないでください。
		/// </summary>
		private void InitializeComponent()
		{
			this._chkAxisI = new System.Windows.Forms.CheckBox();
			this._chkAxisC = new System.Windows.Forms.CheckBox();
			this._chkAxisB = new System.Windows.Forms.CheckBox();
			this._chkAxisA = new System.Windows.Forms.CheckBox();
			this._chkAxisZ = new System.Windows.Forms.CheckBox();
			this._chkAxisW = new System.Windows.Forms.CheckBox();
			this._chkAxisY = new System.Windows.Forms.CheckBox();
			this._chkAxisX = new System.Windows.Forms.CheckBox();
			this.label8 = new System.Windows.Forms.Label();
			this._edtAxisI = new System.Windows.Forms.NumericUpDown();
			this.label7 = new System.Windows.Forms.Label();
			this._edtAxisC = new System.Windows.Forms.NumericUpDown();
			this.label6 = new System.Windows.Forms.Label();
			this._edtAxisB = new System.Windows.Forms.NumericUpDown();
			this.label5 = new System.Windows.Forms.Label();
			this._edtAxisA = new System.Windows.Forms.NumericUpDown();
			this.label3 = new System.Windows.Forms.Label();
			this._edtAxisZ = new System.Windows.Forms.NumericUpDown();
			this.label2 = new System.Windows.Forms.Label();
			this._edtAxisW = new System.Windows.Forms.NumericUpDown();
			this.label1 = new System.Windows.Forms.Label();
			this._edtAxisY = new System.Windows.Forms.NumericUpDown();
			this.label4 = new System.Windows.Forms.Label();
			this._edtAxisX = new System.Windows.Forms.NumericUpDown();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisI)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisC)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisB)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisA)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisZ)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisW)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisY)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisX)).BeginInit();
			this.SuspendLayout();
			// 
			// _chkAxisI
			// 
			this._chkAxisI.AutoSize = true;
			this._chkAxisI.Location = new System.Drawing.Point(45, 272);
			this._chkAxisI.Name = "_chkAxisI";
			this._chkAxisI.Size = new System.Drawing.Size(15, 14);
			this._chkAxisI.TabIndex = 75;
			this._chkAxisI.UseVisualStyleBackColor = true;
			// 
			// _chkAxisC
			// 
			this._chkAxisC.AutoSize = true;
			this._chkAxisC.Location = new System.Drawing.Point(45, 235);
			this._chkAxisC.Name = "_chkAxisC";
			this._chkAxisC.Size = new System.Drawing.Size(15, 14);
			this._chkAxisC.TabIndex = 74;
			this._chkAxisC.UseVisualStyleBackColor = true;
			// 
			// _chkAxisB
			// 
			this._chkAxisB.AutoSize = true;
			this._chkAxisB.Location = new System.Drawing.Point(45, 198);
			this._chkAxisB.Name = "_chkAxisB";
			this._chkAxisB.Size = new System.Drawing.Size(15, 14);
			this._chkAxisB.TabIndex = 73;
			this._chkAxisB.UseVisualStyleBackColor = true;
			// 
			// _chkAxisA
			// 
			this._chkAxisA.AutoSize = true;
			this._chkAxisA.Location = new System.Drawing.Point(45, 161);
			this._chkAxisA.Name = "_chkAxisA";
			this._chkAxisA.Size = new System.Drawing.Size(15, 14);
			this._chkAxisA.TabIndex = 72;
			this._chkAxisA.UseVisualStyleBackColor = true;
			// 
			// _chkAxisZ
			// 
			this._chkAxisZ.AutoSize = true;
			this._chkAxisZ.Location = new System.Drawing.Point(45, 124);
			this._chkAxisZ.Name = "_chkAxisZ";
			this._chkAxisZ.Size = new System.Drawing.Size(15, 14);
			this._chkAxisZ.TabIndex = 71;
			this._chkAxisZ.UseVisualStyleBackColor = true;
			// 
			// _chkAxisW
			// 
			this._chkAxisW.AutoSize = true;
			this._chkAxisW.Location = new System.Drawing.Point(45, 87);
			this._chkAxisW.Name = "_chkAxisW";
			this._chkAxisW.Size = new System.Drawing.Size(15, 14);
			this._chkAxisW.TabIndex = 70;
			this._chkAxisW.UseVisualStyleBackColor = true;
			// 
			// _chkAxisY
			// 
			this._chkAxisY.AutoSize = true;
			this._chkAxisY.Location = new System.Drawing.Point(45, 50);
			this._chkAxisY.Name = "_chkAxisY";
			this._chkAxisY.Size = new System.Drawing.Size(15, 14);
			this._chkAxisY.TabIndex = 69;
			this._chkAxisY.UseVisualStyleBackColor = true;
			// 
			// _chkAxisX
			// 
			this._chkAxisX.AutoSize = true;
			this._chkAxisX.Location = new System.Drawing.Point(45, 13);
			this._chkAxisX.Name = "_chkAxisX";
			this._chkAxisX.Size = new System.Drawing.Size(15, 14);
			this._chkAxisX.TabIndex = 68;
			this._chkAxisX.UseVisualStyleBackColor = true;
			// 
			// label8
			// 
			this.label8.AutoSize = true;
			this.label8.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label8.Location = new System.Drawing.Point(6, 262);
			this.label8.Name = "label8";
			this.label8.Size = new System.Drawing.Size(16, 24);
			this.label8.TabIndex = 67;
			this.label8.Text = "I";
			// 
			// _edtAxisI
			// 
			this._edtAxisI.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtAxisI.Location = new System.Drawing.Point(66, 260);
			this._edtAxisI.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtAxisI.Minimum = new decimal(new int[] {
            1215752191,
            23,
            0,
            -2147483648});
			this._edtAxisI.Name = "_edtAxisI";
			this._edtAxisI.Size = new System.Drawing.Size(156, 31);
			this._edtAxisI.TabIndex = 66;
			this._edtAxisI.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label7
			// 
			this.label7.AutoSize = true;
			this.label7.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label7.Location = new System.Drawing.Point(1, 225);
			this.label7.Name = "label7";
			this.label7.Size = new System.Drawing.Size(26, 24);
			this.label7.TabIndex = 65;
			this.label7.Text = "C";
			// 
			// _edtAxisC
			// 
			this._edtAxisC.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtAxisC.Location = new System.Drawing.Point(66, 223);
			this._edtAxisC.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtAxisC.Minimum = new decimal(new int[] {
            1215752191,
            23,
            0,
            -2147483648});
			this._edtAxisC.Name = "_edtAxisC";
			this._edtAxisC.Size = new System.Drawing.Size(156, 31);
			this._edtAxisC.TabIndex = 64;
			this._edtAxisC.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label6
			// 
			this.label6.AutoSize = true;
			this.label6.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label6.Location = new System.Drawing.Point(1, 188);
			this.label6.Name = "label6";
			this.label6.Size = new System.Drawing.Size(25, 24);
			this.label6.TabIndex = 63;
			this.label6.Text = "B";
			// 
			// _edtAxisB
			// 
			this._edtAxisB.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtAxisB.Location = new System.Drawing.Point(66, 186);
			this._edtAxisB.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtAxisB.Minimum = new decimal(new int[] {
            1215752191,
            23,
            0,
            -2147483648});
			this._edtAxisB.Name = "_edtAxisB";
			this._edtAxisB.Size = new System.Drawing.Size(156, 31);
			this._edtAxisB.TabIndex = 62;
			this._edtAxisB.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label5
			// 
			this.label5.AutoSize = true;
			this.label5.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label5.Location = new System.Drawing.Point(1, 151);
			this.label5.Name = "label5";
			this.label5.Size = new System.Drawing.Size(25, 24);
			this.label5.TabIndex = 61;
			this.label5.Text = "A";
			// 
			// _edtAxisA
			// 
			this._edtAxisA.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtAxisA.Location = new System.Drawing.Point(66, 149);
			this._edtAxisA.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtAxisA.Minimum = new decimal(new int[] {
            1215752191,
            23,
            0,
            -2147483648});
			this._edtAxisA.Name = "_edtAxisA";
			this._edtAxisA.Size = new System.Drawing.Size(156, 31);
			this._edtAxisA.TabIndex = 60;
			this._edtAxisA.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label3
			// 
			this.label3.AutoSize = true;
			this.label3.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label3.Location = new System.Drawing.Point(1, 114);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(24, 24);
			this.label3.TabIndex = 59;
			this.label3.Text = "Z";
			// 
			// _edtAxisZ
			// 
			this._edtAxisZ.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtAxisZ.Location = new System.Drawing.Point(66, 112);
			this._edtAxisZ.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtAxisZ.Minimum = new decimal(new int[] {
            1215752191,
            23,
            0,
            -2147483648});
			this._edtAxisZ.Name = "_edtAxisZ";
			this._edtAxisZ.Size = new System.Drawing.Size(156, 31);
			this._edtAxisZ.TabIndex = 58;
			this._edtAxisZ.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label2.Location = new System.Drawing.Point(1, 77);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(28, 24);
			this.label2.TabIndex = 57;
			this.label2.Text = "W";
			// 
			// _edtAxisW
			// 
			this._edtAxisW.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtAxisW.Location = new System.Drawing.Point(66, 75);
			this._edtAxisW.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtAxisW.Minimum = new decimal(new int[] {
            1215752191,
            23,
            0,
            -2147483648});
			this._edtAxisW.Name = "_edtAxisW";
			this._edtAxisW.Size = new System.Drawing.Size(156, 31);
			this._edtAxisW.TabIndex = 56;
			this._edtAxisW.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label1
			// 
			this.label1.AutoSize = true;
			this.label1.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label1.Location = new System.Drawing.Point(1, 40);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(24, 24);
			this.label1.TabIndex = 55;
			this.label1.Text = "Y";
			// 
			// _edtAxisY
			// 
			this._edtAxisY.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtAxisY.Location = new System.Drawing.Point(66, 38);
			this._edtAxisY.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtAxisY.Minimum = new decimal(new int[] {
            1215752191,
            23,
            0,
            -2147483648});
			this._edtAxisY.Name = "_edtAxisY";
			this._edtAxisY.Size = new System.Drawing.Size(156, 31);
			this._edtAxisY.TabIndex = 54;
			this._edtAxisY.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// label4
			// 
			this.label4.AutoSize = true;
			this.label4.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this.label4.Location = new System.Drawing.Point(1, 3);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(24, 24);
			this.label4.TabIndex = 53;
			this.label4.Text = "X";
			// 
			// _edtAxisX
			// 
			this._edtAxisX.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
			this._edtAxisX.Location = new System.Drawing.Point(66, 1);
			this._edtAxisX.Maximum = new decimal(new int[] {
            1215752191,
            23,
            0,
            0});
			this._edtAxisX.Minimum = new decimal(new int[] {
            1215752191,
            23,
            0,
            -2147483648});
			this._edtAxisX.Name = "_edtAxisX";
			this._edtAxisX.Size = new System.Drawing.Size(156, 31);
			this._edtAxisX.TabIndex = 52;
			this._edtAxisX.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			// 
			// UserCoordinate
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this._chkAxisI);
			this.Controls.Add(this._chkAxisC);
			this.Controls.Add(this._chkAxisB);
			this.Controls.Add(this._chkAxisA);
			this.Controls.Add(this._chkAxisZ);
			this.Controls.Add(this._chkAxisW);
			this.Controls.Add(this._chkAxisY);
			this.Controls.Add(this._chkAxisX);
			this.Controls.Add(this.label8);
			this.Controls.Add(this._edtAxisI);
			this.Controls.Add(this.label7);
			this.Controls.Add(this._edtAxisC);
			this.Controls.Add(this.label6);
			this.Controls.Add(this._edtAxisB);
			this.Controls.Add(this.label5);
			this.Controls.Add(this._edtAxisA);
			this.Controls.Add(this.label3);
			this.Controls.Add(this._edtAxisZ);
			this.Controls.Add(this.label2);
			this.Controls.Add(this._edtAxisW);
			this.Controls.Add(this.label1);
			this.Controls.Add(this._edtAxisY);
			this.Controls.Add(this.label4);
			this.Controls.Add(this._edtAxisX);
			this.Name = "UserCoordinate";
			this.Size = new System.Drawing.Size(222, 295);
			this.Load += new System.EventHandler(this.UserCoordinate_Load);
			((System.ComponentModel.ISupportInitialize)(this._edtAxisI)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisC)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisB)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisA)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisZ)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisW)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisY)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this._edtAxisX)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.CheckBox _chkAxisI;
		private System.Windows.Forms.CheckBox _chkAxisC;
		private System.Windows.Forms.CheckBox _chkAxisB;
		private System.Windows.Forms.CheckBox _chkAxisA;
		private System.Windows.Forms.CheckBox _chkAxisZ;
		private System.Windows.Forms.CheckBox _chkAxisW;
		private System.Windows.Forms.CheckBox _chkAxisY;
		private System.Windows.Forms.CheckBox _chkAxisX;
		private System.Windows.Forms.Label label8;
		private System.Windows.Forms.NumericUpDown _edtAxisI;
		private System.Windows.Forms.Label label7;
		private System.Windows.Forms.NumericUpDown _edtAxisC;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.NumericUpDown _edtAxisB;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.NumericUpDown _edtAxisA;
		private System.Windows.Forms.Label label3;
		private System.Windows.Forms.NumericUpDown _edtAxisZ;
		private System.Windows.Forms.Label label2;
		private System.Windows.Forms.NumericUpDown _edtAxisW;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.NumericUpDown _edtAxisY;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.NumericUpDown _edtAxisX;
	}
}
