// <auto-generated />
namespace DebugMcIf
{
	partial class UserAxisFlags
	{
		/// <summary> 
		/// 必要なデザイナー変数です。
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// 使用中のリソースをすべてクリーンアップします。
		/// </summary>
		/// <param name="disposing">マネージ リソースを破棄する場合は true を指定し、その他の場合は false を指定します。</param>
		protected override void Dispose( bool disposing )
		{
			if( disposing && ( components != null ) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region コンポーネント デザイナーで生成されたコード

		/// <summary> 
		/// デザイナー サポートに必要なメソッドです。このメソッドの内容を 
		/// コード エディターで変更しないでください。
		/// </summary>
		private void InitializeComponent()
		{
			this._chkAxisI = new System.Windows.Forms.CheckBox();
			this._chkAxisC = new System.Windows.Forms.CheckBox();
			this._chkAxisB = new System.Windows.Forms.CheckBox();
			this._chkAxisA = new System.Windows.Forms.CheckBox();
			this._chkAxisZ = new System.Windows.Forms.CheckBox();
			this._chkAxisW = new System.Windows.Forms.CheckBox();
			this._chkAxisY = new System.Windows.Forms.CheckBox();
			this._chkAxisX = new System.Windows.Forms.CheckBox();
			this.SuspendLayout();
			// 
			// _chkAxisI
			// 
			this._chkAxisI.AutoSize = true;
			this._chkAxisI.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkAxisI.Location = new System.Drawing.Point(246, 3);
			this._chkAxisI.Name = "_chkAxisI";
			this._chkAxisI.Size = new System.Drawing.Size(24, 16);
			this._chkAxisI.TabIndex = 1;
			this._chkAxisI.Text = "I";
			this._chkAxisI.UseVisualStyleBackColor = true;
			// 
			// _chkAxisC
			// 
			this._chkAxisC.AutoSize = true;
			this._chkAxisC.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkAxisC.Location = new System.Drawing.Point(211, 3);
			this._chkAxisC.Name = "_chkAxisC";
			this._chkAxisC.Size = new System.Drawing.Size(29, 16);
			this._chkAxisC.TabIndex = 2;
			this._chkAxisC.Text = "C";
			this._chkAxisC.UseVisualStyleBackColor = true;
			// 
			// _chkAxisB
			// 
			this._chkAxisB.AutoSize = true;
			this._chkAxisB.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkAxisB.Location = new System.Drawing.Point(176, 3);
			this._chkAxisB.Name = "_chkAxisB";
			this._chkAxisB.Size = new System.Drawing.Size(29, 16);
			this._chkAxisB.TabIndex = 3;
			this._chkAxisB.Text = "B";
			this._chkAxisB.UseVisualStyleBackColor = true;
			// 
			// _chkAxisA
			// 
			this._chkAxisA.AutoSize = true;
			this._chkAxisA.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkAxisA.Location = new System.Drawing.Point(141, 3);
			this._chkAxisA.Name = "_chkAxisA";
			this._chkAxisA.Size = new System.Drawing.Size(29, 16);
			this._chkAxisA.TabIndex = 4;
			this._chkAxisA.Text = "A";
			this._chkAxisA.UseVisualStyleBackColor = true;
			// 
			// _chkAxisZ
			// 
			this._chkAxisZ.AutoSize = true;
			this._chkAxisZ.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkAxisZ.Location = new System.Drawing.Point(107, 3);
			this._chkAxisZ.Name = "_chkAxisZ";
			this._chkAxisZ.Size = new System.Drawing.Size(28, 16);
			this._chkAxisZ.TabIndex = 5;
			this._chkAxisZ.Text = "Z";
			this._chkAxisZ.UseVisualStyleBackColor = true;
			// 
			// _chkAxisW
			// 
			this._chkAxisW.AutoSize = true;
			this._chkAxisW.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkAxisW.Location = new System.Drawing.Point(71, 3);
			this._chkAxisW.Name = "_chkAxisW";
			this._chkAxisW.Size = new System.Drawing.Size(30, 16);
			this._chkAxisW.TabIndex = 6;
			this._chkAxisW.Text = "W";
			this._chkAxisW.UseVisualStyleBackColor = true;
			// 
			// _chkAxisY
			// 
			this._chkAxisY.AutoSize = true;
			this._chkAxisY.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkAxisY.Location = new System.Drawing.Point(37, 3);
			this._chkAxisY.Name = "_chkAxisY";
			this._chkAxisY.Size = new System.Drawing.Size(28, 16);
			this._chkAxisY.TabIndex = 7;
			this._chkAxisY.Text = "Y";
			this._chkAxisY.UseVisualStyleBackColor = true;
			// 
			// _chkAxisX
			// 
			this._chkAxisX.AutoSize = true;
			this._chkAxisX.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this._chkAxisX.Location = new System.Drawing.Point(3, 3);
			this._chkAxisX.Name = "_chkAxisX";
			this._chkAxisX.Size = new System.Drawing.Size(28, 16);
			this._chkAxisX.TabIndex = 8;
			this._chkAxisX.Text = "X";
			this._chkAxisX.UseVisualStyleBackColor = true;
			// 
			// UserAxisFlags
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.Controls.Add(this._chkAxisI);
			this.Controls.Add(this._chkAxisC);
			this.Controls.Add(this._chkAxisB);
			this.Controls.Add(this._chkAxisA);
			this.Controls.Add(this._chkAxisZ);
			this.Controls.Add(this._chkAxisW);
			this.Controls.Add(this._chkAxisY);
			this.Controls.Add(this._chkAxisX);
			this.Name = "UserAxisFlags";
			this.Size = new System.Drawing.Size(273, 22);
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.CheckBox _chkAxisI;
		private System.Windows.Forms.CheckBox _chkAxisC;
		private System.Windows.Forms.CheckBox _chkAxisB;
		private System.Windows.Forms.CheckBox _chkAxisA;
		private System.Windows.Forms.CheckBox _chkAxisZ;
		private System.Windows.Forms.CheckBox _chkAxisW;
		private System.Windows.Forms.CheckBox _chkAxisY;
		private System.Windows.Forms.CheckBox _chkAxisX;
	}
}
